---
permalink: deploy/concept_supported_storage_system_and_applications.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere 用の ONTAP ツールの導入を開始する前に、ストレージシステムの基本要件、アプリケーション要件、およびライセンス要件について理解しておく必要があります。 
---
= ONTAP ツールでサポートされているストレージシステム、ライセンス、およびアプリケーション
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere 用の ONTAP ツールの導入を開始する前に、ストレージシステムの基本要件、アプリケーション要件、およびライセンス要件について理解しておく必要があります。

サポートされる ONTAP 、 vCenter Server 、 ESXi ホスト、プラグインアプリケーション、および Site Recovery Manager （ SRM ）のバージョンの最新情報については、 Interoperability Matrix Tool （ IMT ）を参照してください。

https://imt.netapp.com/matrix/imt.jsp?components=103229;&solution=1777&isHWU&src=IMT["Interoperability Matrix Tool で確認してください"]

VMware Virtual Volumes （ vVol ）データストアに対して仮想マシンの Snapshot 処理とクローン処理を実行するためには、 FlexClone ライセンスを有効にする必要があります。

Storage Replication Adapter （ SRA ）には次のライセンスが必要です。

* SnapMirror ライセンス
+
SRA のフェイルオーバー処理を実行するためには、 SnapMirror ライセンスを有効にする必要があります。

* FlexClone ライセンス
+
SRA のテストフェイルオーバー処理を実行するためには、 FlexClone ライセンスを有効にする必要があります。



データストアの IOPS を表示するには、 Storage I/O Control を有効にするか、 Storage I/O Control の設定でストレージ I/O 統計の収集を無効にするチェックボックスをオフにする必要があります。Storage I/O Control は、 VMware の Enterprise Plus ライセンスがある場合にのみ有効にできます。

* https://kb.vmware.com/s/article/1022091["Storage I/O Control のトラブルシューティング"]
* https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.resmgmt.doc/GUID-37CC0E44-7BC7-479C-81DC-FFFC21C1C4E3.html["Storage I/O Control の要件"]

