---
permalink: deploy/concept_configure_your_storage_system_environment.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere 用の ONTAP ® ツールでは、ストレージシステムの検出とストレージクレデンシャルの設定を単一のメカニズムで行います。クレデンシャルに基づいて、 Virtual Storage Console （ VSC ）ユーザがストレージシステムを使用してタスクを実行するために必要な ONTAP 権限が付与されます。 
---
= ONTAP tools for VMware vSphereストレージシステムを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere 用の ONTAP ® ツールでは、ストレージシステムの検出とストレージクレデンシャルの設定を単一のメカニズムで行います。クレデンシャルに基づいて、 Virtual Storage Console （ VSC ）ユーザがストレージシステムを使用してタスクを実行するために必要な ONTAP アクセス許可が付与されます。

VSC でストレージリソースを表示して管理するには、まずストレージシステムを検出しなければなりません。検出プロセスでは、ストレージシステムの ONTAP クレデンシャルが必要になります。これはユーザ名とパスワードのペアに関連付けられた権限（ロール）で、ストレージシステムごとに割り当てられます。これらのユーザ名とパスワードのペアは、 ONTAP RBAC を使用するため、 ONTAP で設定する必要があります。これらのクレデンシャルを VSC で変更することはできません。ONTAP RBAC ロールは、 ONTAP システムマネージャを使用して定義できます。


NOTE: 管理者としてログインすると、そのストレージシステムに対するすべての権限が自動的に付与されます。

VSC にストレージシステムを追加するときは、ストレージシステムの IP アドレス、およびそのシステムに関連付けられているユーザ名とパスワードのペアを入力する必要があります。VSC がストレージシステムの検出プロセスで使用するデフォルトクレデンシャルを設定することも、ストレージシステムが検出されたときにクレデンシャルを手動で入力することもできます。VSC に追加されるストレージシステムの詳細は、導入環境で有効にする拡張機能に自動的にプッシュされます。VASA Provider と Storage Replication Adapter （ SRA ）にストレージを手動で追加する必要はありません。VSC と SRA は、クラスタレベルおよび Storage Virtual Machine （ SVM ）レベルでクレデンシャルの追加をサポートします。VASA Provider は、ストレージシステムを追加するためのクラスタレベルのクレデンシャルのみをサポートします。ストレージシステムを追加する場合は、ONTAP toolsプラグインとストレージシステム間の通信を相互認証する必要があります。

環境に複数の vCenter Server インスタンスが含まれている場合、ストレージシステムページから VSC にストレージシステムを追加するときに、ストレージシステムを追加する vCenter Server ボックスが表示されます。このボックスで、ストレージシステムを追加する vCenter Server インスタンスを指定できます。データセンター名を右クリックしてストレージシステムを追加する場合は、そのデータセンターにサーバがすでに関連付けられているため、 vCenter Server インスタンスを指定するオプションは表示されません。

検出は、次のいずれかの方法で実行されます。いずれの場合も、新たに検出されるすべてのストレージシステムのクレデンシャルを指定する必要があります。

* VSC サービスが開始されると、 VSC の自動バックグラウンド検出プロセスが開始されます。
* [ストレージシステム]ページの*[すべて再検出]*ボタンをクリックするか、ホストまたはデータセンターで*[操作]*メニュー（*[操作]*>*[NetApp ONTAP tools]*>*[ホストデータとストレージデータの更新]*）から選択できます。概要セクションの [ はじめに ] タブで * 発見 * をクリックすることもできます。


VSC の機能を使用してタスクを実行するときは、いずれも特定の権限が必要です。ユーザが実行できる操作は、 ONTAP ロールに関連付けられたクレデンシャルに基づいて制限できます。ストレージシステムのユーザ名とパスワードのペアを同じにすれば、複数のユーザで同じストレージシステムのクレデンシャルを共有し、同じ処理を実行することができます。
