---
permalink: deploy/concept_installation_workflow_for_existing_users_of_ontap_tools.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere 用の ONTAP ツール 9.x リリースでは、最新バージョンへのインプレースアップグレードがサポートされています。 
---
= ONTAP ツールの既存ユーザ向けの導入ワークフロー
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere 用の ONTAP ツール 9.x リリースでは、最新バージョンへのインプレースアップグレードがサポートされています。

ONTAP ツールなどの個々のアプリケーションの以前のリリースでは、異なるアップグレードプロセスが使用されます。VSC 、 VASA Provider 、または SRA がインストールされている環境では、次の処理を実行する必要があります。

. 最新リリースの ONTAP ツールを導入します。
. 既存の設定データを移行します。
+
構成データにはストレージ・システムのクレデンシャルのほかに 'kaminoprefs.xml ファイルおよび vscPreferences.xml ファイルで使用されるプリファレンスも含まれます



link:../configure/reference_set_ipv4_or_ipv6.html["プリファレンスファイルを使用して IPv4 または IPv6 を設定してください"]

多くの場合、設定データを移行する必要はありません。ただし、以前にプリファレンスファイルをカスタマイズした場合は、それらのファイルを確認し、新しく導入した ONTAP ツールに対しても同様の変更を行うことを推奨します。次のいずれかを実行できます。

* 使用 https://mysupport.netapp.com/tools/index.html["SnapCenter および Virtual Storage Console 用の NetApp インポートユーティリティ"] をクリックして、ストレージシステムのクレデンシャルを VSC 6.X および SRA 4.X から新しい導入環境に移行します。
* 新しく導入した ONTAP ツールにストレージシステムを追加し、クレデンシャルを指定して追加します。


VASA Provider 6.X からアップグレードする場合は、アップグレード前に VASA Provider の登録を解除する必要があります。詳細については、ご使用のリリースのドキュメントを参照してください。

SRA 4.0 以前からのアップグレードも実施する場合は、次の手順を実行します。

* SRA 4.0P1 を使用している場合は、まず SRA 9.6 にアップグレードする必要があります。その後、 SRA 9.6 から最新リリースへのインプレースアップグレードを実行できます。
+
link:../deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html["ONTAP ツールの最新リリースにアップグレードします"]

* SRA 2.1 または 3.0 を使用している場合は、最初に既存のサイトの設定をメモしておく必要があります。
+
ONTAP 用 Storage Replication Adapter 4.0 のインストールおよびセットアップガイドの詳細な手順については、「アップグレードの概要」を参照してください。これらの SRA リリースも VASA Provider を使用するため、 VASA Provider の登録を解除してから最新バージョンの ONTAP ツールを導入する必要があります。アップグレードが完了したら、以前のリリースのサーバ（「 .ova 」）を削除できます。



SRA をアップグレードする場合は、 SRA ソフトウェア（ .msi ファイルによってインストールされた、 Site Recovery Manager サーバ上のアダプタ）を Site Recovery Manager サーバから削除する必要があります。Windows システムのコントロールパネルを使用してソフトウェアをアンインストールし、最新の SRA ソフトウェアを .msi ファイルを使用して SRA サーバにインストールできます。

VASA Provider を導入している場合は、既存のセットアップからアップグレードしたあと、「設定の編集」オプションを使用して ONTAP ツールのメモリサイズを 12GB に設定する必要があります。仮想メモリの予約も変更する必要があります。メモリサイズを変更するには、仮想マシンの電源をオフにする必要があります。

セットアップに 7.2 または 7.2.1 リリースの ONTAP ツールがある場合は、 9.7P1 以降の ONTAP ツールに直接アップグレードできません。まず既存の環境を ONTAP ツール 9.7 にアップグレードしてから、最新リリースにアップグレードする必要があります。

最新リリースの ONTAP ツールを導入する場合は ' ONTAP ツールの導入要件を参照してください インプレース・アップグレードの実行方法については、「 Upgrading to the 9.8 release of ONTAP tools 」を参照してください。

* 関連情報 *

https://mysupport.netapp.com/site/tools[]
