---
permalink: deploy/reference_deployment_customization_requirements.html 
sidebar: sidebar 
keywords:  
summary: 導入 ONTAP ツールをカスタマイズするときは、いくつかの制限事項について考慮する必要があります。 
---
= 導入のカスタマイズに関する考慮事項
:icons: font
:imagesdir: ../media/


[role="lead"]
導入 ONTAP ツールをカスタマイズするときは、いくつかの制限事項について考慮する必要があります。



== アプライアンスの管理者ユーザのパスワード

管理者パスワードにはスペースは使用できません。



== アプライアンスのメンテナンスコンソールのクレデンシャル

メンテナンスコンソールにアクセスするには、「 maint 」ユーザ名を使用する必要があります。導入時に「 maint 」ユーザのパスワードを設定できます。パスワードを変更するには、 ONTAP ツールのメンテナンスコンソールの [ アプリケーションの設定 ] メニューを使用します。



== vCenter Server 管理者のクレデンシャル

ONTAP ツールの導入時に vCenter Server の管理者クレデンシャルを設定できます。

vCenter Server のパスワードが変更になった場合、 URL ： \https://<IP>:8143/Register.html を使用して管理者のパスワードを更新できます。この IP アドレスは、導入時に指定した ONTAP ツールの IP アドレスです。



== vCenter Server の IP アドレス

* ONTAP ツールを登録する vCenter Server インスタンスの IP アドレス（ IPv4 または IPv6 ）を指定する必要があります。
+
生成される VSC 証明書と VASA 証明書のタイプは、導入時に指定した IP アドレス（ IPv4 または IPv6 ）によって異なります。ONTAP ツールの導入時に静的 IP の詳細と DHCP を入力しなかった場合は、 IPv4 アドレスと IPv6 アドレスの両方がネットワークから提供されます。

* vCenter Server への登録に使用する ONTAP ツールの IP アドレスは、導入ウィザードで入力した vCenter Server の IP アドレスのタイプ（ IPv4 または IPv6 ）によって異なります。
+
vCenter Server の登録時に使用したものと同じタイプの IP アドレスを使用して、 VSC と VASA の両方の証明書が生成されます。

+

NOTE: ： IPv6 は vCenter Server 6.7 以降でのみサポートされます。





== アプライアンスのネットワーク・プロパティ

DHCP を使用していない場合は、有効な DNS ホスト名（非修飾）と ONTAP ツールの静的 IP アドレス、およびその他のネットワークパラメータを指定します。これらのパラメータはすべて、適切なインストールと運用のために必要です。
