---
permalink: deploy/reference_port_requirements_for_vsc.html 
sidebar: sidebar 
keywords: port requirements 
summary: ストレージシステムと VMware vCenter Server の間の通信など、 Virtual Storage Console \ （ VSC\ ）のコンポーネント間の通信には、指定のポートがデフォルトで使用されます。ファイアウォールを有効にしている場合は、例外を許可するようにファイアウォールを設定する必要があります。 
---
= VSC のポート要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージシステムと VMware vCenter Server の間の通信など、 Virtual Storage Console （ VSC ）のコンポーネント間の通信には、指定のポートがデフォルトで使用されます。ファイアウォールを有効にしている場合は、例外を許可するようにファイアウォールを設定する必要があります。

Windows 以外のファイアウォールについては、 VSC で使用する特定のポートへのアクセスを手動で許可する必要があります。これらのポートへのアクセスを許可しないと、次のようなエラーメッセージが表示されます。

「サーバと通信できません。

VSC で使用されるデフォルトの双方向 TCP ポートは次のとおりです。

|===


| * デフォルトのポート番号 * | * 概要 * 


 a| 
9083 年
 a| 
有効にすると、 VASA Provider と Storage Replication Adapter （ SRA ）の両方がこのポートを使用して vCenter Server と通信します。このポートは TCP/IP 設定を取得するためにも必要です。このポートは、VPサポートバンドルのダウンロード、Web CLIユーザインターフェイスへのアクセス、およびVMwareからVPへのパス通信の制御に使用されます。



 a| 
443
 a| 
クレデンシャルの設定方法によっては、 VMware vCenter Server とストレージシステムがこのポートでセキュアな通信をリスンします。このポートは、クライアント/サーバ間の通信アーキテクチャで使用されます。443ポートは、セキュアな接続に対してデフォルトで有効になっています。REST APIを使用する任意のオートメーションクライアントであるクライアントがサーバへの接続を開始し、エンドポイントがデータを交換します。



 a| 
8143
 a| 
VSC は、このポートでセキュアな通信をリスンします。このポートは、クライアント/サーバ間の通信アーキテクチャで使用されます。REST APIを使用する任意のオートメーションクライアントであるクライアントがサーバへの接続を開始し、エンドポイントがデータを交換します。このポートは、VSCサービスおよびVSCサーバログのエクスポートで有効になります。register.htmlページはこのポートでホストされます。REST swaggerはこのポートで公開されています。

|===

NOTE: ONTAP ツールを導入する前に、 Internet Control Message Protocol （ ICMP ）を有効にしておく必要があります。

ICMP が無効になっていると、 ONTAP ツールの初期設定が失敗し、導入後に VSC が VSC サービスと VASA Provider サービスを開始できなくなります。導入後に、 VSC サービスと VASA Provider サービスを手動で有効にする必要があります。
