---
permalink: deploy/task_install_the_nfs_vaai_plug_in.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere 用の ONTAP ツールの GUI を使用して、ネットアップ NFS Plug-in for VMware vStorage APIs for Array Integration （ VAAI ）をインストールできます。 
---
= NFS VAAI プラグインをインストールします
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere 用 ONTAP ツールの GUI を使用して、ネットアップ NFS Plug-in for VMware vStorage APIs for Array Integration （ VAAI ）をインストールできます。

* 必要なもの *

* NetApp Support Site から NFS Plug-in for VAAI (`.vib') のインストールパッケージをダウンロードしておく必要があります。
+
https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"]

* ESXi ホスト 6.5 以降と ONTAP 9.1 以降をインストールしておく必要があります。
* ESXi ホストの電源をオンにし、 NFS データストアをマウントしておく必要があります。
* 「 ataMover.HardwareAcceleratedMove 」、「 DataMover.HardwareAcceleratedInit 」、および「 VMFS3.HardwareAcceleratedLocking 」の値を「 1` 」に設定しておく必要があります。
+
これらの値は、推奨設定ダイアログボックスが更新されると、 ESXi ホストで自動的に設定されます。

* vserver nfs modify -vserver vserver_name -vStorage enabled` コマンドを使用して、 Storage Virtual Machine （ SVM ）の vstorage オプションを有効にしておく必要があります。
* NetApp NFS VAAI Plug-in 2.0 を使用している場合は、 ESXi 7.0 update1 以降が必要です。


* 手順 *

. ネットアップサポートサイトからダウンロードした「 .vib 」ファイルの名前を、 VSC で使用する事前定義された名前に変更します。
. ONTAP ツールのホームページで「 * 設定」をクリックします。
. NFS VAAI ツール * タブをクリックします。
. [ 既存のバージョン * （ Existing version * ） ] セクションで [ * 変更 * （ Change * ） ] をクリックする
. 名前を変更した「 .vib` 」ファイルを参照して選択し、「 * アップロード」をクリックしてファイルを ONTAP ツールにアップロードします。
. ESXi ホストにインストールセクションで、 NFS VAAI プラグインをインストールする ESXi ホストを選択し、 * インストール * をクリックします。
+
画面に表示される手順に従ってインストールを完了する必要があります。インストールの進行状況は、 vSphere Web Client のタスクセクションで監視できます。

. インストールが終了したら、 ESXi ホストをリブートします。
+
ESXi ホストをリブートすると、 NFS VAAI プラグインが VSC で自動的に検出されます。プラグインを有効にするための追加の手順は必要ありません。


