---
permalink: deploy/task_clean_the_vsphere_cached_downloaded_plug_in_packages.html 
sidebar: sidebar 
keywords: clean up browser cache 
summary: ONTAP ツールの導入またはアップグレード後にプラグインが自動的に更新されない場合は、ブラウザおよび vCenter Server 上にキャッシュされているダウンロード済みプラグインパッケージをクリーンアップして、 vCenter Server プラグインの問題を解決する必要があります。 
---
= vSphere にキャッシュされているダウンロード済みプラグインパッケージをクリアします
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ツールの導入またはアップグレード後にプラグインが自動的に更新されない場合は、ブラウザおよび vCenter Server にキャッシュされているダウンロード済みプラグインパッケージをクリーンアップして、 vCenter Server プラグインの問題を解決する必要があります。

* 手順 *

. 既存の vSphere Web Client または vSphere Client からログアウトします。
. ブラウザキャッシュを削除します。
. vSphere Client にキャッシュされたプラグインパッケージを削除します。
+
|===


| * を使用している場合 * | * 次の手順を実行します。 * 


 a| 
Windows vCenter Server の場合
 a| 
次の場所にある com.netapp.vasa.vvol.webclient-x.x.x.xxxx` 、 com.netapp.nvpf.webclient-x.x.x.xxxx` 、および com.netapp.vsch5-x.x.x.xxxx` フォルダを削除します。

** vSphere Web Client のパス： C ： \ProgramData\VMware\vCenterServer\cfg\vsphere-client\vc-packages\vsphere-client-serenity
** vSphere Client （ HTML5 ）のパス：「 C ： \ProgramData\VMware\vCenterServer\cfg\vsphere-ui\vc-packages\vsphere-client-serenity 」




 a| 
vCSA
 a| 
.. SSH で VCSA アプライアンスに接続します。
.. cd /etc/vmware/vsphere-client/vc-packages/vsphere-client-serenity を使用して、 vCenter Web Client UI 拡張ディレクトリにディレクトリを変更します
.. 「 rm -rf 」コマンドを使用して、ネットアップに固有のキャッシュされたプラグインパッケージを削除します。例：ここで、 x.x.x.xxxx はプラグインのバージョンです。--rm -rf com.netapp.vasa.vvol.webclient-x.x.x.xxxx rm -rf com.netapp.nvpf.webclient-x.x.x.xxxx rm -rf com.netapp.vsch5-x.x.x.xxxx ----
.. 「 cd /etc/vmware/vsphere-clientui/vc-packages/vsphere-client-serenity 」を使用して、ディレクトリを vCenter クライアント（ HTML5 ） UI 拡張ディレクトリに変更します
.. 「 rm -rf 」コマンドを使用して、ネットアッププラグインに固有のキャッシュされたプラグインパッケージを削除します。例： here x.x.x.xxxx は、プラグインのバージョンです。 --rm -rf com.netapp.vasa.vvol.webclient-x.x.x.xxxx rm -rf com.netapp.nvpf.webclient-x.x.x.xxxx rm -rf com.netapp.vsch5-x.x.x.xxxx ----


|===
. vSphere にログインし、次のコマンドを使用して vSphere Web Client サービスと vSphere Client サービスを再起動します。
+
[listing]
----
service-control --stop vsphere-client vsphere-ui
service-control --start vsphere-client vsphere-ui
----

