---
permalink: deploy/task_deploy_ontap_tools.html 
sidebar: sidebar 
keywords:  
summary: アプライアンスを使用するには、環境に ONTAP ツールを導入し、必要なパラメータを指定する必要があります。 
---
= ONTAP ツールの導入方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アプライアンスを使用するには、環境に ONTAP ツールを導入し、必要なパラメータを指定する必要があります。

* 必要なもの *

* サポートされているリリースの vCenter Server が実行されている必要があります。
+

NOTE: ONTAP ツールは、 Windows 環境の vCenter Server または VMware vCenter Server Virtual Appliance （ vCSA ）環境に登録できます。

+
https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Interoperability Matrix Tool で確認してください"^]

* vCenter Server 環境を設定およびセットアップしておく必要があります。
* 仮想マシン用の ESXi ホストのセットアップが完了している必要があります。
* .ova ファイルをダウンロードしておく必要があります。
* vCenter Server インスタンスの管理者のログインクレデンシャルが必要です。
* vSphere Client のすべてのブラウザセッションからログアウトして、ブラウザを閉じておきます。また、 ONTAP ツールの導入時にブラウザキャッシュの問題がブラウザキャッシュに表示されないように、ブラウザキャッシュを削除しておく必要があります。
* Internet Control Message Protocol（ICMP）を有効にしておく必要があります。
+
ICMP が無効になっていると、 ONTAP ツールの初期設定が失敗し、導入後に VSC が VSC サービスと VASA Provider サービスを開始できなくなります。導入後に、 VSC サービスと VASA Provider サービスを手動で有効にする必要があります。



* このタスクについて *

ONTAP ツールを新規に導入する場合は、デフォルトで VASA Provider が有効になります。ただし、以前のリリースの ONTAP ツールからアップグレードする場合は、アップグレード前の VASA Provider の状態が維持されるため、 VASA Provider を手動で有効にしなければならないことがあります。

link:../deploy/task_enable_vasa_provider_for_configuring_virtual_datastores.html["仮想データストアを設定するための VASA Provider の有効化"]

* 手順 *

. vSphere Client にログインします。
. [ホーム]*>*[ホストおよびクラスタ]*を選択します。
. 目的のデータセンターを右クリックし、*[OVFテンプレートのデプロイ...]*をクリックします。
. ONTAP ツールの導入ファイルを提供する方法を選択し、 * 次へ * をクリックします。
+
|===


| * 場所 * | * アクション * 


 a| 
URL
 a| 
ONTAP ツールの _.ova ファイルの URL を指定します。



 a| 
フォルダ
 a| 
.ovaファイルを含む.zipファイルをローカルシステムに展開します。[Select an OVF template]ページで、解凍したフォルダ内の.ovaファイルの場所を指定します。

|===
. 詳細を入力して、導入ウィザードをカスタマイズします。
+
（オプション） Configure vCenter （ vCenter の構成）または Enable VCF （ VCF を有効にする）セクションで、 * Enable VMware Cloud Foundation （ VCF ） * チェックボックスを選択し、 ONTAP ツールの資格情報のパスワードを入力します。IP アドレスを指定する必要はありませんが、パスワードを指定する必要があります。詳細については、以下を参照してください。

+
** link:../deploy/reference_considerations_for_deploying_ontap_tools_for_vmware_vsphere.html["導入のカスタマイズに関する考慮事項"]
** link:../deploy/vmware_cloud_foundation_mode_deployment.html["ONTAP ツールの VMware Cloud Foundation 配置モード"]


. 構成データを確認し、 [ 次へ * ] をクリックして導入を終了します。
+
展開が完了するまで待つ間に、 [ タスク ] タブから展開の進行状況を表示できます。

. ONTAP Tools 仮想マシンの電源をオンにし、 ONTAP ツールを実行している仮想マシンのコンソールを開きます。
. 導入の完了後に、 ONTAP ツールが実行されていることを確認します。
. ONTAP toolsがどのvCenter Serverにも登録されていない場合は、を使用します `\https://appliance_ip:8143/Register.html` をクリックしてVSCインスタンスを登録します。Register.htmlに、swaggerページにリダイレクトされます。ONTAP tools 9.12以降では、SwaggerページからvCenterへのONTAP toolsの登録が行われます。
+
9.12以降では、POST APIを使用してONTAP toolsをvCenterに登録します。

+
[listing]
----
/2.0/plugin/vcenter
----
. vSphere Client からログアウトして再度ログインすると、導入した ONTAP ツールが表示されます。
+
vSphere Client でプラグインが更新されるまでに数分かかる場合があります。

+
* トラブルシューティング： * ログインしてもプラグインが表示されない場合は、 vSphere Client のキャッシュをクリーンアップする必要があります。

+
link:../deploy/task_clean_the_vsphere_cached_downloaded_plug_in_packages.html["vSphere にキャッシュされているダウンロード済みプラグインパッケージをクリアします"]



link:../deploy/task_enable_vasa_provider_for_configuring_virtual_datastores.html["仮想データストアを設定するための VASA Provider の有効化"]

* 関連情報 *

https://kb.netapp.com/?title=Advice_and_Troubleshooting%2FData_Storage_Software%2FVirtual_Storage_Console_for_VMware_vSphere%2FError_during_fresh_deployment_of_virtual_appliance_for_VSC%252C_VASA_Provider%252C_and_SRA["VSC 、 VASA Provider 、 SRA 仮想アプライアンスの新規導入時にエラーが発生する"]
