---
permalink: protect/reference_configure_storage_replication_adapter_for_highly_scaled_environment.html 
sidebar: sidebar 
keywords:  
summary: 大規模な環境で最適なパフォーマンスを実現するには、 Storage Replication Adapter （ SRA ）の推奨設定に従ってストレージのタイムアウト間隔を設定する必要があります。 
---
= 大規模な環境向けの Storage Replication Adapter の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
大規模な環境で最適なパフォーマンスを実現するには、 Storage Replication Adapter （ SRA ）の推奨設定に従ってストレージのタイムアウト間隔を設定する必要があります。



== ストレージプロバイダの設定

拡張環境の SRM について、次のタイムアウト値を設定する必要があります。

|===


| * 詳細設定 * | * タイムアウト値 * 


 a| 
「 torageProvider.resignatureTimeout 」を参照してください
 a| 
設定の値を 900 秒から 12000 秒に増やします。



 a| 
'torageProvider.hostRescanDelaySec'
 a| 
60



 a| 
'torageProvider.hostRescanRepeatCnt'
 a| 
20



 a| 
'torageProvider.hostRescanTimeoutSec'
 a| 
高い値を設定します（例： 99999 ）

|===
また、「 torageProvider.autoResignatureMode` 」オプションを有効にする必要があります。

ストレージプロバイダの設定を変更する方法の詳細については、 VMware のドキュメントを参照してください。

https://docs.vmware.com/en/Site-Recovery-Manager/6.5/com.vmware.srm.admin.doc/GUID-E4060824-E3C2-4869-BC39-76E88E2FF9A0.html["VMware vSphere のドキュメント：「ストレージプロバイダ設定の変更"]



== ストレージ設定

大規模な環境では、「 torage.commandTimeout` 」および「 storage-.maxConcurrentCommandCnt 」のタイムアウト間隔の値を 99 、 999 秒に設定する必要があります。


NOTE: 指定したタイムアウト間隔が最大値です。最大タイムアウトに達することはありません。ほとんどのコマンドは、設定された最大タイムアウト間隔内に終了します。

また、 vvol.properties ファイル offtap.operation.timeout.period.seconds=86400 で、 SRA が 1 回の処理を実行する最大時間を設定する必要があります。

https://kb.netapp.com/mgmt/OTV/SRA/NetApp_Storage_Replication_Adapter_4.0%2F%2F7.X_for_ONTAP_Sizing_Guide["ネットアップナレッジベースの回答 1001111 ：「 NetApp Storage Replication Adapter 4.0/7.X for ONTAP Sizing Guide"]

詳細については、 SAN プロバイダの設定の変更に関する VMware のドキュメントを参照してください。

https://docs.vmware.com/en/Site-Recovery-Manager/index.html?hWord=N4IghgNiBcIGoFkDuYBOBTABAZQJYBcsAldAYwHsA3dVAT0wTADswBzGzAEXNIFcBbdE3xh8uckxABfIA["VMware Site Recovery Manager のドキュメント：「ストレージ設定の変更"]
