---
permalink: protect/reference_configure_storage_replication_adapter_for_highly_scaled_environment.html 
sidebar: sidebar 
keywords:  
summary: 大規模な環境で最適なパフォーマンスを実現するには、 Storage Replication Adapter （ SRA ）の推奨設定に従ってストレージのタイムアウト間隔を設定する必要があります。 
---
= 大規模な環境向けの Storage Replication Adapter の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
大規模な環境で最適なパフォーマンスを実現するには、 Storage Replication Adapter （ SRA ）の推奨設定に従ってストレージのタイムアウト間隔を設定する必要があります。



== ストレージプロバイダの設定

拡張環境の SRM について、次のタイムアウト値を設定する必要があります。

|===


| * 詳細設定 * | * タイムアウト値 * 


 a| 
「 torageProvider.resignatureTimeout 」を参照してください
 a| 
設定の値を 900 秒から 12000 秒に増やします。



 a| 
'torageProvider.hostRescanDelaySec'
 a| 
60



 a| 
'torageProvider.hostRescanRepeatCnt'
 a| 
20



 a| 
'torageProvider.hostRescanTimeoutSec'
 a| 
高い値を設定します（例： 99999 ）

|===
また、「 torageProvider.autoResignatureMode` 」オプションを有効にする必要があります。

ストレージプロバイダの設定の変更の詳細については、Broadcomのマニュアルを参照してください。

https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/site-recovery-manager/8-8/site-recovery-manager-administration-8-8/advanced-srm-configuration/reconfigure-srm-settings/change-storage-provider-settings.html["Change Storage Provider Settings"]



== ストレージ設定

タイムアウトに達した場合は、 `storage.commandTimeout` および `storage.maxConcurrentCommandCnt` 値を大きくします。


NOTE: 指定したタイムアウト間隔が最大値です。最大タイムアウトに達することはありません。ほとんどのコマンドは、設定された最大タイムアウト間隔内に終了します。

また、 vvol.properties ファイル offtap.operation.timeout.period.seconds=86400 で、 SRA が 1 回の処理を実行する最大時間を設定する必要があります。

https://kb.netapp.com/mgmt/OTV/SRA/NetApp_Storage_Replication_Adapter_4.0%2F%2F7.X_for_ONTAP_Sizing_Guide["ネットアップナレッジベースの回答 1001111 ：「 NetApp Storage Replication Adapter 4.0/7.X for ONTAP Sizing Guide"]

詳細については、SANプロバイダの設定の変更に関するBroadcomのドキュメントを参照してください。

https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/site-recovery-manager/8-8/site-recovery-manager-administration-8-8/advanced-srm-configuration/reconfigure-srm-settings/change-storage-settings.html["Change Storage Settings"]
