---
permalink: protect/task_pair_protected_and_recovery_sites.html 
sidebar: sidebar 
keywords:  
summary: Storage Replication Adapter （ SRA ）でストレージシステムを検出できるようにするには、作成された保護対象サイトとリカバリサイトを vSphere Client を使用してペアリングする必要があります。 
---
= 保護対象サイトとリカバリサイトをペアリング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Replication Adapter （ SRA ）でストレージシステムを検出できるようにするには、作成された保護対象サイトとリカバリサイトを vSphere Client を使用してペアリングする必要があります。

* 必要なもの *

* 保護対象サイトとリカバリサイトに Site Recovery Manager （ SRM ）がインストールされている必要があります。
* 保護対象サイトとリカバリサイトに SRA がインストールされている必要があります。


* このタスクについて *

SnapMirrorのファンアウト構成は、ソースボリュームが2つの異なるデスティネーションにレプリケートされる構成です。SRMがデスティネーションから仮想マシンをリカバリする必要がある場合、リカバリ中に問題が発生します。* 手順 *

. vSphere Client のホームページで [ サイトのリカバリ ] をダブルクリックし、 [ サイト ] をクリックします。
. [ * オブジェクト * > * アクション * > * サイトのペアリング * ] をクリックします。
. ペアサイトリカバリマネージャサーバーダイアログボックスで、保護サイトのプラットフォームサービスコントローラのアドレスを入力し、次へ * をクリックします。
. Select vCenter Server セクションで、次の手順を実行します。
+
.. 保護対象サイトの vCenter Server が対応するペア候補として表示されていることを確認します。
.. SSO 管理クレデンシャルを入力し、 [* 終了 * ] をクリックします。


. プロンプトが表示されたら、 [ はい ] をクリックしてセキュリティ証明書を受け入れます。


* 結果 *

保護対象サイトとリカバリサイトの両方が [ オブジェクト ] ダイアログボックスに表示されます。
