---
permalink: protect/task_map_storage_policies.html 
sidebar: sidebar 
keywords:  
summary: リカバリ計画でリカバリされた仮想マシンをマッピングに基づいて適切なデータストアに配置するには、保護対象サイトのストレージポリシーをリカバリサイトのストレージポリシーにマッピングする必要があります。リカバリサイトで仮想マシンのリカバリが完了すると、マッピングされた VM ストレージポリシーが仮想マシンに割り当てられます。 
---
= ストレージポリシーをマッピングする
:icons: font
:imagesdir: ../media/


[role="lead"]
リカバリ計画でリカバリされた仮想マシンをマッピングに基づいて適切なデータストアに配置するには、保護対象サイトのストレージポリシーをリカバリサイトのストレージポリシーにマッピングする必要があります。リカバリサイトで仮想マシンのリカバリが完了すると、マッピングされた VM ストレージポリシーが仮想マシンに割り当てられます。

* 手順 *

. vSphere Client で、 * Site Recovery * > * Open Site Recovery * をクリックします。
. [ サイトペア ] タブで、 [ * 構成 *>* ストレージポリシーマッピング * ] をクリックします。
. 必要なサイトを選択し、 * New * をクリックして新しいマッピングを作成します。
. オプション * Automatically prepare mappings for storage policies with matching names * を選択し、 * next* をクリックします。
+
SRM は、同じ名前のストレージポリシーがリカバリサイトに存在する保護対象サイト上のストレージポリシーを選択します。手動マッピングオプションを選択して、複数のストレージポリシーを選択することもできます。

. [ マッピングの追加 * ] をクリックし、 [ 次へ * ] をクリックします。
. [ * リバースマッピング * （ * Reverse mapping * ） ] セクションで、マッピングに必要なチェックボックスを選択し、 [ * 次へ * （ * next * ） ] をクリックします。
. [ 完了準備完了（ * Ready to Complete ） ] セクションで選択内容を確認し、 [ 完了（ * Finish ） ] をクリックします。

