---
permalink: protect/task_configure_storage_replication_adapter_for_san_environment.html 
sidebar: sidebar 
keywords:  
summary: Site Recovery Manager 用の Storage Replication Adapter \ （ SRA \ ）を実行するには、事前にストレージシステムのセットアップが必要です。 
---
= SAN 環境向けの Storage Replication Adapter の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Site Recovery Manager （ SRM ）向け Storage Replication Adapter （ SRA ）を実行するには、事前にストレージシステムのセットアップが必要です。

* 必要なもの *

保護対象サイトとリカバリサイトに次のプログラムがインストールされている必要があります。

* SRM の場合
+
SRM のインストールについては、 VMware サイトのドキュメントを参照してください。

+
https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/site-recovery-manager/8-7/site-recovery-manager-installation-and-configuration-8-7/overview-of-vmware-site-recovery-manager.html["VMware Site Recovery Manager のドキュメント"]

* SRA
+
アダプタは SRM にインストールされます。



* 手順 *

. 保護対象サイトで、プライマリ ESXi ホストがプライマリストレージシステムの LUN に接続されていることを確認します。
. プライマリ・ストレージ・システムで、「 ostype 」オプションが _vmware_ に設定されている igroup に、 LUN が含まれていることを確認します。
. リカバリサイトの ESXi ホストが FC または iSCSI を使用して Storage Virtual Machine （ SVM ）に適切に接続されていることを確認します。セカンダリサイトのESXiホストはセカンダリサイトのストレージにアクセスできる必要があります。同様に、プライマリサイトのESXiホストはプライマリサイトのストレージにアクセスできる必要があります。
+
そのためには、ESXiホストのローカルLUNがSVM上で接続されていることを確認するか、を使用します `fcp show initiators` コマンドまたはを実行します `iscsi show initiators` SVMでコマンドを実行します。
ESXiホストでマッピングされたLUNへのLUNアクセスをチェックして、FC接続とiSCSI接続を確認します。





== NAS 環境向けの Storage Replication Adapter の設定

* 必要なもの *

保護対象サイトとリカバリサイトに次のプログラムがインストールされている必要があります。

* SRM の場合
+
SRM のインストールに関するドキュメントは、 VMware のサイトで入手できます。

+
https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/site-recovery-manager/8-7/site-recovery-manager-installation-and-configuration-8-7/overview-of-vmware-site-recovery-manager.html["VMware Site Recovery Manager のドキュメント"]

* SRA
+
SRM と SRA サーバにアダプタをインストールします。



* 手順 *

. 保護対象サイトのデータストアに、 vCenter Server に登録された仮想マシンがあることを確認します。
. 保護対象サイトの ESXi ホストに、 Storage Virtual Machine （ SVM ）の NFS エクスポートボリュームがマウントされていることを確認します。
. Array Manager ウィザードを使用して SRM にアレイを追加するときに、 NFS エクスポートが存在する IP アドレス、ホスト名、 FQDN などの有効なアドレスが *NFS Address* フィールドに指定されていることを確認します。
. リカバリサイトの各 ESXi ホストで「 ping 」コマンドを実行して、 SVM から NFS エクスポートへの接続に使用される IP アドレスにホストの VMkernel ポートからアクセスできることを確認します。


https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"]
