---
permalink: concepts/concept_manage_disaster_recovery_setup_using_srm.html 
sidebar: sidebar 
keywords:  
summary: VMware の Site Recovery Manager\ （ SRM\ ）とともに、 vCenter Server でディザスタリカバリの設定を作成および管理できます。 
---
= ディザスタリカバリを設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ディザスタリカバリの設定は、 VMware の Site Recovery Manager （ SRM ）とともに vCenter Server で作成および管理できます。

VASA Provider に Storage Replication Adapter （ SRA ）の機能が組み込まれました。データセンターで VVOL データストアを設定している場合は、 VVOL データストアのリカバリ用に、ディザスタリカバリ用に SRA を別途インストールする必要はありません。Site Recovery Manager （ SRM ）で、保護対象サイトとリカバリサイトをペアリングする必要があります。サイトをペアリングしたら、 SRM の次の設定作業としてアレイペアを設定します。アレイペアにより、 SRM がストレージシステムと通信してデバイスとデバイスのレプリケーションを検出できるようになります。アレイペアを設定する前に、まず SRM でサイトペアを作成する必要があります。

このリリースの ONTAP ツールには、ディザスタリカバリに同期 SnapMirror 設定を使用するオプションがあります。


NOTE: VMware Site Recovery Manager （ SRM ）では、 VVOL データストアのディザスタリカバリの管理に SRA は使用されません。代わりに、 ONTAP 9.7 以降のクラスタの VVOL データストアのレプリケーションとフェイルオーバー制御に VASA Provider を使用します。

link:../protect/task_enable_storage_replication_adapter.html["Storage Replication Adapter を有効にする"]
