---
permalink: concepts/concept_guidelines_for_using_vsc_standard_roles.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere の標準的な ONTAP ® ツールを使用する場合は、一定のガイドラインに従う必要があります。 
---
= ONTAP toolsの標準ロールの使用に関するガイドライン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere の標準的な ONTAP ® ツールを使用する場合は、一定のガイドラインに従う必要があります。

標準ロールは直接変更しないでください。このオプションを選択すると、ONTAP toolsをアップグレードするたびにONTAP toolsによって変更が上書きされます。ONTAP toolsをアップグレードするたびに、インストーラによって標準ロール定義が更新されます。これにより、使用しているバージョンのONTAP toolsだけでなく、サポートされるすべてのバージョンのvCenter Serverでロールが最新の状態に維持されます。

ただし、標準のロールを使用して環境に合わせたロールを作成することもできます。これを行うには、ONTAP toolsの標準ロールをコピーしてから、コピーしたロールを編集する必要があります。新しいロールを作成すると、ONTAP tools Windowsサービスを再起動またはアップグレードしても、このロールを維持できます。

ONTAP toolsの標準ロールを使用する方法には、次のようなものがあります。

* ONTAP toolsのすべてのタスクには、標準のONTAP toolsロールを使用します。
+
このシナリオでは、標準ロールには、ONTAP toolsタスクを実行するために必要なすべての権限が含まれています。

* 複数のロールを組み合わせてユーザが実行できるタスクを拡張する。
+
ONTAP toolsの標準ロールの方が細かすぎる場合は、複数のロールを含む上位レベルのグループを作成してロールを拡張できます。

+
ユーザがvCenter Server標準の追加権限を必要とするONTAP tools以外のタスクを実行する必要がある場合は、それらの権限を提供するロールを作成してグループに追加できます。

* より細分化されたロールを作成します。
+
標準のONTAP toolsロールよりも制限の厳しいロールを実装する必要がある場合は、ONTAP toolsロールを使用して新しいロールを作成できます。

+
この場合は、必要なONTAP toolsロールのクローンを作成し、そのクローンロールを編集してユーザに必要な権限のみを付与します。


