---
permalink: concepts/concept_virtual_storage_console_overview.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere 用の ONTAP ツールは、ネットアップストレージシステムを使用する VMware 環境の仮想マシンに対して、エンドツーエンドのライフサイクル管理を提供します。管理者はvCenter Server内でストレージを直接管理できるため、VMware環境のストレージとデータの管理が簡易化されます。 
---
= ONTAP ツールの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere 用の ONTAP ツールは、ネットアップストレージシステムを使用する VMware 環境の仮想マシンに対して、エンドツーエンドのライフサイクル管理を提供します。管理者はvCenter Server内でストレージを直接管理できるため、VMware環境のストレージとデータの管理が簡易化されます。

ONTAP ツールは vSphere Client と統合されており、シングルサインオン（ SSO ）サービスを利用できます。vCenter Serverインスタンスが複数ある環境では、管理する各vCenter ServerインスタンスにONTAP toolsの独自のインスタンスを登録する必要があります。

ONTAP ツールの各コンポーネントは、ストレージをより効率的に管理するための機能を提供します。

VMware vSphere Clientプラグインツールは、vCenter Server内で実行することなく、プラグイン機能をvSphere Clientに統合するように設計されています。これにより、プラグインが分離され、大規模なvSphere環境で動作するプラグインをスケールアウトできます。



== Virtual Storage Console （ VSC ）

VSC では次の作業を実行できます。

* SRA と VASA Provider の両方で利用できるストレージコントローラを追加し、クレデンシャルを割り当て、 VSC のストレージコントローラのアクセス許可を設定する
* データストアをプロビジョニング
* vCenter Server 環境でデータストアと仮想マシンのパフォーマンスを監視します
* Role-Based Access Control （ RBAC ；ロールベースアクセス制御）を使用して、次の 2 つのレベルで vCenter Server オブジェクトへの管理者アクセスを制御します。
+
** 仮想マシンやデータストアなどの vSphere オブジェクト
+
これらのオブジェクトの管理には vCenter Server RBAC を使用します。

** ONTAP ストレージ
+
ストレージシステムの管理には ONTAP RBAC を使用します。



* ネットアップストレージに接続されている ESXi ホストのホスト設定を表示および更新します


NFS Plug-in for VMware vStorage APIs for Array Integration （ VAAI ）を使用することは、 VSC のプロビジョニング処理にメリットがあります。NFS Plug-in for VAAI は、 ESXi ホストにインストールされている VMware の仮想ディスクライブラリを統合するソフトウェアライブラリです。VMware VAAI パッケージを使用すると、特定のタスクを物理ホストからストレージアレイにオフロードできます。シンプロビジョニングやハードウェアアクセラレーションなどのタスクをアレイレベルで実行して、 ESXi ホスト上のワークロードを削減できます。コピーオフロード機能やスペースリザベーション機能によって、 VSC の処理のパフォーマンスが向上します。

NetApp NFS Plug-in for VAAI は VSC に付属していません。ただし、ネットアップサポートサイトから、このプラグインのインストールパッケージをダウンロードして、インストール手順を確認できます。



== VASA Provider

VASA Provider for ONTAP は、 VMware vSphere APIs for Storage Awareness （ VASA ）を使用して、 VMware vSphere で使用されているストレージに関する情報を vCenter Server に送信します。ONTAP のツールには、 VASA Provider と VSC が統合されています。VASA Provider では次の作業を実行できます。

* VMware 仮想ボリューム（ vVol ）データストアをプロビジョニングする
* 環境に応じた異なるストレージのサービスレベル目標（ SLO ）を定義するストレージ機能プロファイルを作成して使用します
* データストアがストレージ機能プロファイルに準拠しているかどうかを確認する
* ボリュームやアグリゲートがしきい値に近づいたときに警告するようにアラームを設定します
* VVol データストアに作成された仮想マシンディスク（ VMDK ）と仮想マシンのパフォーマンスを監視する




== Storage Replication Adapter （ SRA ）

SRA を有効にして VMware Site Recovery Manager （ SRM ）と一緒に使用している場合、障害時に vCenter Server のデータストアと仮想マシンをリカバリできます。SRA を使用すると、障害時のディザスタリカバリに、保護対象サイトとリカバリサイトにアレイベースのレプリケーション（ ABR ）を使用できます。

* 関連情報 *

https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"]
