---
permalink: concepts/concept_privileges_required_for_vsc_tasks.html 
sidebar: sidebar 
keywords:  
summary: ONTAP Tools for VMware vSphereのタスクごとに、ONTAP Tools for VMware vSphere固有の権限とvCenter Server標準の権限の組み合わせが異なります。 
---
= ONTAP toolsのタスクに必要な権限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP Tools for VMware vSphereのタスクごとに、ONTAP Tools for VMware vSphere固有の権限とvCenter Server標準の権限の組み合わせが異なります。

ONTAP toolsのタスクに必要な権限については、NetAppの技術情報アーティクル1032542を参照してください。

https://kb.netapp.com/data-mgmt/OTV/VSC_Kbs/VSC_VASA_and_SRA_ONTAP_RBAC_Configuration["ONTAP Tools for VMware vSphere：RBACの設定"]



== VMware vSphere 用の ONTAP ツールで必要な製品レベルの権限

ONTAP tools for VMware vSphere GUIにアクセスするには、製品レベルのONTAP tools固有のView権限が、適切なvSphereオブジェクトレベルで割り当てられている必要があります。この権限なしでログインすると、NetAppアイコンをクリックしたときにONTAP toolsにエラーメッセージが表示され、ONTAP toolsにアクセスできなくなります。

View *権限では、ONTAPツールGUIにアクセスできます。ONTAP tools内でタスクを実行することはできません。ONTAP toolsのタスクを実行するには、タスクに対して適切なONTAP tools固有の権限とvCenter Server標準の権限が必要です。

割り当てレベルによって、表示できる UI の部分が決まります。ルートオブジェクト（フォルダ）でView権限を割り当てると、NetAppアイコンをクリックしてONTAP toolsにアクセスできるようになります。

別のvSphereオブジェクトレベルにView権限を割り当てることもできますが、その場合は表示および使用できるONTAP toolsメニューが制限されます。

View 権限を含むアクセス許可は、ルートオブジェクトに割り当てることを推奨します。
