---
permalink: concepts/concept_standard_roles_packaged_with_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: vCenter Server の権限と RBAC を簡単に使用できるように、 Virtual Storage Console （ VSC ）には主要な VSC タスクを実行できる標準の VSC ロールが用意されています。また、タスクの実行を制限し、 VSC 情報の表示のみを許可する読み取り専用ロールもあります。 
---
= ONTAP ツールに付属の標準ロール
:icons: font
:imagesdir: ../media/


[role="lead"]
vCenter Server の権限と RBAC を簡単に使用できるように、 Virtual Storage Console （ VSC ）には主要な VSC タスクを実行できる標準の VSC ロールが用意されています。また、タスクの実行を制限し、 VSC 情報の表示のみを許可する読み取り専用ロールもあります。

標準の VSC ロールには、ユーザが VSC タスクを実行するために必要な VSC 固有の権限と vCenter Server 標準の権限の両方が含まれています。また、サポートされるどのバージョンの vCenter Server でも必要な権限が付与されるように設定されています。

管理者は、必要に応じてこれらのロールをユーザに割り当てることができます。


NOTE: VSC を最新バージョンにアップグレードした場合は、新しいバージョンの VSC で使用できるように自動的にアップグレードされます。

VSC の標準ロールは、 vSphere Client のホームページで * Roles * をクリックすると表示できます。

VSC の組み込みのロールで実行できるタスクを次に示します。

|===


| * 役割 * | * 概要 * 


 a| 
VSC 管理者
 a| 
すべての VSC タスクを実行するために必要な vCenter Server 標準の権限と VSC 固有の権限がすべて含まれています。



 a| 
VSC 読み取り専用
 a| 
VSC に対する読み取り専用アクセスが許可されます。アクセスが制御された VSC の処理は実行できません。



 a| 
VSC によるプロビジョニング
 a| 
ストレージのプロビジョニングに必要な vCenter Server 標準の権限と VSC 固有の権限がすべて含まれています。次のタスクを実行できます。

* 新しいデータストアを作成する
* データストアを削除
* ストレージ機能プロファイルに関する情報を表示する


|===


== VSC の標準ロールの使用に関するガイドライン

VMware vSphere の標準的な ONTAP ® ツールを使用する場合は、一定のガイドラインに従う必要があります。

標準ロールは直接変更しないでください。ロールを直接変更すると、 VSC をアップグレードするたびに変更が上書きされます。VSC をアップグレードするたびに、インストーラによって標準ロールの定義が更新されます。これにより、そのバージョンの VSC およびサポートされるすべてのバージョンの vCenter Server でロールを最新の状態に維持できます。

ただし、標準のロールを使用して環境に合わせたロールを作成することもできます。これを行うには、 VSC の標準ロールをコピーし、コピーしたロールを編集します。新しいロールを作成しても、 VSC Windows サービスを再起動またはアップグレードしてもこのロールを維持できます。

VSC の標準ロールの用途としては、次のようなものがあります。

* すべての VSC タスクに標準の VSC ロールを使用する。
+
このシナリオでは、標準ロールは VSC タスクの実行に必要なすべての権限をユーザに提供します。

* 複数のロールを組み合わせてユーザが実行できるタスクを拡張する。
+
単独では要件に合う標準の VSC ロールがない場合は、複数のロールを含む上位グループを作成してロールを拡張できます。

+
ユーザが vCenter Server 標準の別の権限を必要とする VSC 以外のタスクも実行する必要がある場合は、それらの権限を提供するロールを作成し、グループに追加します。

* より細分化されたロールを作成します。
+
標準の VSC ロールよりも少ない権限のロールが必要な場合は、 VSC ロールを使用して新しいロールを作成することができます。

+
この場合は、必要な VSC ロールのクローンを作成し、そのクローンを編集してユーザに必要な権限だけを残します。


