---
permalink: concepts/reference_metrocluster_configurations_supported_by_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere 用の ONTAP ツールでは、 ONTAP の MetroCluster IP 構成と FC 構成を使用する環境がサポートされます。このサポートはほぼ自動的に行われます。ただし、 MetroCluster 環境で VSC および VASA Provider を使用している場合はいくつかの違いがあります。 
---
= ONTAP ツールでサポートされる MetroCluster 構成
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere 用の ONTAP ツールでは、 ONTAP の MetroCluster IP 構成と FC 構成を使用する環境がサポートされます。このサポートはほぼ自動的に行われます。ただし、 MetroCluster 環境で VSC および VASA Provider を使用している場合はいくつかの違いがあります。


NOTE: SRA では、 MetroCluster 構成がサポートされません。



== MetroCluster 構成と VSC

プライマリサイトとセカンダリサイトで VSC がストレージシステムコントローラを検出することを確認する必要があります。通常、 VSC は自動的にストレージコントローラを検出します。クラスタ管理 LIF を使用している場合は、 VSC が両方のサイトでクラスタを検出していることを確認することを推奨します。検出されていない場合は、手動でストレージコントローラを VSC に追加できます。VSC がストレージコントローラへの接続に使用するユーザ名とパスワードのペアを変更することもできます。

スイッチオーバーが発生した場合、セカンダリサイトの SVM がテイクオーバーします。これらの SVM には、名前に「 -mc 」というサフィックスがつけられています。データストアのプロビジョニングなどの処理の実行中にスイッチオーバー処理が発生すると、データストアが存在する SVM の名前が「 -mc 」サフィックスのついたものに変わります。スイッチバックが発生してプライマリサイトの SVM に制御が戻ると、このサフィックスは削除されます。


NOTE: MetroCluster 構成の直接接続 SVM を VSC に追加した場合は、スイッチオーバー後に SVM 名の変更（「 -mc 」サフィックスの追加）が反映されません。他のスイッチオーバー操作は、いずれも引き続き通常どおりに実行されます。

スイッチオーバーまたはスイッチバック後、 VSC で自動的にクラスタが検出されて認識されるまでに数分かかる場合があります。データストアのプロビジョニングなどの VSC 処理を実行中にスイッチオーバーまたはスイッチバックが発生した場合、処理に遅れが生じることがあります。



== MetroCluster 構成と VASA Provider

VASA Provider では、 MetroCluster 構成を使用する環境が自動的にサポートされます。VASA Provider 環境では、スイッチオーバーは透過的に行われます。直接接続 SVM を VASA Provider に追加することはできません。


NOTE: VASA Provider では、スイッチオーバーの実行後にセカンダリサイトの SVM の名前に「 -mc 」というサフィックスが付加されません。
