---
permalink: configure/concept_configure_storage_systems_for_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: ストレージシステムをONTAP tools for VMware vSphereに追加し、必要に応じてONTAP toolsのインターフェイスを使用してデフォルトクレデンシャルを設定します。 
---
= ONTAP ツール用のストレージシステムの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージシステムをONTAP tools for VMware vSphereに追加し、必要に応じてONTAP toolsのインターフェイスを使用してデフォルトクレデンシャルを設定します。

VMware vSphere 用の ONTAP ツールでは、ストレージシステムの検出とストレージクレデンシャルの設定を単一のメカニズムで行います。クレデンシャルに基づいて、ONTAP toolsユーザがストレージシステムを使用してタスクを実行するために必要なONTAP権限が付与されます。

ONTAPツールでストレージリソースを表示して管理するには、ONTAPツールでストレージシステムを検出する必要があります。検出プロセスでは、ストレージシステムの ONTAP クレデンシャルが必要になります。これはユーザ名とパスワードのペアに関連付けられた権限（ロール）で、ストレージシステムごとに割り当てられます。これらのユーザ名とパスワードのペアは、 ONTAP RBAC を使用するため、 ONTAP で設定する必要があります。これらのクレデンシャルをONTAP toolsで変更することはできません。ONTAP RBAC ロールは、 ONTAP システムマネージャを使用して定義できます。


NOTE: 管理者としてログインすると、そのストレージシステムに対するすべての権限が自動的に付与されます。

ONTAP toolsにストレージシステムを追加する場合は、ストレージシステムのIPアドレスと、そのシステムに関連付けられているユーザ名とパスワードのペアを指定する必要があります。ONTAP toolsがストレージシステムの検出プロセスで使用するデフォルトクレデンシャルを設定することも、ストレージシステムが検出されたときにクレデンシャルを手動で入力することもできます。ONTAP tools for VMware vSphereに追加されるストレージシステムの詳細は、導入環境で有効にする拡張機能に自動的にプッシュされます。VASA Provider と Storage Replication Adapter （ SRA ）にストレージを手動で追加する必要はありません。ONTAP tools for VMware vSphereとSRAは、クラスタレベルとStorage Virtual Machine（SVM）レベルでクレデンシャルの追加をサポートします。VASA Provider は、ストレージシステムを追加するためのクラスタレベルのクレデンシャルのみをサポートします。ストレージシステムを追加する場合は、ONTAP toolsプラグインとストレージシステム間の通信を相互認証する必要があります。

環境に複数のvCenter Serverインスタンスが含まれている場合に[ストレージシステム]ページからONTAP toolsにストレージシステムを追加すると、[ストレージシステムの追加]ダイアログボックスに[vCenter Server]ボックスが表示され、ストレージシステムを追加するvCenter Serverインスタンスを指定できます。データセンター名を右クリックしてストレージシステムを追加する場合は、そのデータセンターにサーバがすでに関連付けられているため、 vCenter Server インスタンスを指定するオプションは表示されません。

検出は、次のいずれかの方法で実行されます。いずれの場合も、新たに検出されるすべてのストレージシステムのクレデンシャルを指定する必要があります。

* ONTAP toolsサービスが開始されると、ONTAP toolsは自動バックグラウンド検出プロセスを開始します。
* [ ストレージシステム * ] ページ、またはホスト / データセンターの [ すべて再検出 ] ボタンをクリックして、 [ アクション * ] メニュー（ * アクション * > * NetApp ONTAP ツール * > * ホストおよびストレージデータの更新 * ）から選択できます。「概要」セクションの「はじめに」タブで「 * 発見」をクリックすることもできます。


ONTAP toolsのすべての機能で、タスクを実行するには特定の権限が必要です。ユーザが実行できる操作は、 ONTAP ロールに関連付けられたクレデンシャルに基づいて制限できます。ストレージシステムのユーザ名とパスワードのペアを同じにすれば、複数のユーザで同じストレージシステムのクレデンシャルを共有し、同じ処理を実行することができます。
