---
permalink: configure/concept_requirements_for_registering_vsc_in_multiple_vcenter_servers_environment.html 
sidebar: sidebar 
keywords:  
summary: 単一のVMware vSphere HTML5クライアントで複数のvCenter Serverインスタンスを管理している環境でONTAP®Tools for VMware vSphereを使用している場合は、 tools ONTAPとvCenter Serverを1：1のペアにするためには、各vCenter ServerにONTAP toolsのインスタンスを1つ登録する必要があります。そうすることで、 vCenter 6.0 以降を実行するすべてのサーバを、単一の vSphere HTML5 クライアントからリンクモードと非リンクモードの両方で管理することができます。 
---
= 複数のvCenter Server環境でONTAP Toolsを登録するための要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
単一のVMware vSphere HTML5クライアントで複数のvCenter Serverインスタンスを管理している環境でONTAP Tools for VMware vSphereを使用している場合は、 tools ONTAPとvCenter Serverを1：1のペアにするためには、各vCenter ServerにONTAP toolsのインスタンスを1つ登録する必要があります。これにより、vCenter 7.0以降を実行するすべてのサーバを、単一のvSphere HTML5クライアントからリンクモードと非リンクモードの両方で管理できます。


NOTE: vCenter ServerでONTAP toolsを使用する場合は、管理するvCenter Serverインスタンスごとに1つのONTAP toolsインスタンスをセットアップまたは登録しておく必要があります。登録された各ONTAP toolsインスタンスのバージョンが同じである必要があります。

リンクモードは、 vCenter Server の導入時に自動的に設定されます。リンクモードでは、 Microsoft Active Directory Application Mode （ ADAM ）を使用して、複数の vCenter Server システムにわたってデータが格納され、同期されます。

vSphere HTML5クライアントを使用して複数のvCenter ServerにわたってONTAP toolsタスクを実行するには、次の条件を満たす必要があります。

* VMwareインベントリ内の管理対象のvCenter Serverには、それぞれ1つのONTAP toolsサーバを登録して一意の1：1ペアにする必要があります。
+
たとえば、ONTAP toolsサーバAをvCenter Server Aに登録し、ONTAP toolsサーバBをvCenter Server Bに登録し、ONTAP toolsサーバCをvCenter Server Cに登録します。

+
ONTAP toolsサーバAをvCenter Server AとvCenter Server Bの両方に登録することはできません。

+
VMwareインベントリにONTAP toolsサーバが登録されていないvCenter Serverが含まれているが、ONTAP toolsに登録されているvCenter Serverが1つ以上ある場合は、 その後、ONTAP toolsが登録されているvCenter Serverに対して、ONTAP toolsのインスタンスを表示し、ONTAP toolsの処理を実行できます。

* シングルサインオン（SSO）に登録されたvCenter Serverごとに、ONTAP tools固有のView権限が必要です。
+
適切な RBAC アクセス許可も必要です。



vCenter Serverの指定を必要とするタスクを実行する場合は、画面左上の*インスタンス*セレクタに、使用可能なvCenter Serverがアルファベット順に表示されます。デフォルトの vCenter Server が、常にドロップダウンリストの先頭のサーバとなります。

ストレージの場所が認識されている場合（たとえば、特定の vCenter Server で管理されているホスト上にデータストアがある状態でプロビジョニングウィザードを使用した場合）は、 vCenter Server の一覧が読み取り専用オプションとして表示されます。これは、 vSphere Web Client で右クリックオプションを使用して項目を選択した場合にのみ該当します。

ONTAPツールで管理されていないオブジェクトを選択しようとすると、警告が表示されます。

ONTAP toolsの概要ページでは、特定のvCenter Serverに基づいてストレージシステムをフィルタリングできます。概要ページは、vCenter Serverに登録されているすべてのONTAP toolsインスタンスで表示されます。特定のONTAP toolsインスタンスとvCenter Serverに関連付けられているストレージシステムを管理できますが、ONTAP toolsの複数のインスタンスを実行する場合は、ストレージシステムごとに登録情報を分けておく必要があります。
