---
permalink: configure/concept_configure_storage_capability_profiles.html 
sidebar: sidebar 
keywords: storage capability profiles 
summary: VASA Provider for ONTAP では、ストレージ機能プロファイルを作成して、ストレージにマッピングすることができます。これにより、ストレージ全体で一貫性を維持できます。また、ストレージがストレージ機能プロファイルに準拠しているかどうかについても、 VASA Provider を使用して確認することができます。 
---
= ストレージ機能プロファイルの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VASA Provider for ONTAP では、ストレージ機能プロファイルを作成して、ストレージにマッピングすることができます。これにより、ストレージ全体で一貫性を維持できます。また、ストレージがストレージ機能プロファイルに準拠しているかどうかについても、 VASA Provider を使用して確認することができます。

ストレージ機能はストレージシステムの一連の属性であり、そのストレージ機能が関連付けられているストレージオブジェクトのストレージパフォーマンスのレベル、ストレージ効率、その他の機能（暗号化など）を特定します。

従来のデータストアの場合、ストレージ機能プロファイルを使用して共通の属性を持つ一貫性のあるデータストアを作成し、 QoS ポリシーを割り当てることができます。プロビジョニング時、ONTAP toolsには、ストレージ機能プロファイルに一致するクラスタ、SVM、およびアグリゲートが表示されます。ストレージマッピングメニューの「プロファイルのグローバル自動生成」オプションを使用すると、既存の従来のデータストアからストレージ機能プロファイルを生成できます。プロファイルを作成したら、ONTAPツールを使用してデータストアがプロファイルに準拠しているかどうかを監視できます。


NOTE: 直接接続のSVMではVVolデータストアはサポートされません。

VVol データストアの場合、プロビジョニングウィザードでは、複数のストレージ機能プロファイルを使用してデータストア内に異なる FlexVol を作成できます。VM ストレージポリシーを使用すると、その定義に従って、該当する FlexVol に仮想マシン用の VVol を自動的に作成できます。たとえば、代表的なストレージクラス（パフォーマンス制限や暗号化や FabricPool などの機能）用のプロファイルを作成することができます。あとで、仮想マシンのビジネスクラスを表す VM ストレージポリシーを vCenter Server に作成し、該当するストレージ機能プロファイルに名前（ Production 、 Test 、 HR など）でリンクできます。

VVol で使用する場合は、ストレージ機能プロファイルによって個々の仮想マシンのストレージパフォーマンスも設定され、パフォーマンス要件を最も満たす VVol データストアの FlexVol に仮想マシンが配置されます。QoS ポリシーにパフォーマンスの最小 IOPS または最大 IOPS を指定できます。仮想マシンを最初にプロビジョニングするときはデフォルトのポリシーを使用できます。また、ビジネス要件の変化に応じてあとから VM ストレージポリシーを変更することもできます。


NOTE: ASA-Cストレージ機能プロファイルは、ONTAP tools for VMware vSphere 9.13P1以降でサポートされます。

このリリースの ONTAP ツールのデフォルトのストレージ機能プロファイルは次のとおりです。

* Platinum_AFF_A
* Platinum_AFF_C
* Platinum_asa_a
* Platinum_ASA_C
* AFF_NVMe_AFF_A
* AFF_NVMe_AFF_C
* AFF_NVMe_ASA_A
* AFF_NVMe_ASA_C
* AFF_Thick_AFF_A
* AFF_Thick_AFF_C
* AFF_Thick_ASA_A
* AFF_Thick_ASA_C
* AFF_DEFAULT_AFF_A
* AFF_DEFAULT_AFF_C
* AFF_DEFAULT_ASA_A
* AFF_DEFAULT_ASA_C
* AFF_Tiering_AFF_A
* AFF_Tiering_AFF_C
* AFF_Tiering_ASA_A
* AFF_Tiering_ASA_C
* AFF_Encrypted_AFF_A
* AFF_Encrypted_AFF_C
* AFF_Encrypted_ASA_A
* AFF_Encrypted_ASA_C
* AFF_Encrypted_Tiering_AFF_A
* AFF_Encrypted_Tiering_AFF_C
* AFF_Encrypted_Tiering_ASA_A
* AFF_Encrypted_Tiering_ASA_C
* AFF_Encrypted_Min50_AFF_A
* AFF_Encrypted_Min50_AFF_C
* AFF_Encrypted_Min50_ASA_A
* AFF_Encrypted_Min50_ASA_C
* ブロンズ


vCenter Server は LUN またはボリュームのストレージ機能を、その LUN またはボリュームでプロビジョニングされるデータストアに関連付けます。これにより、仮想マシンのストレージプロファイルに一致するデータストアに仮想マシンをプロビジョニングして、データストアクラスタ内のすべてのデータストアのストレージサービスレベルを同じにすることができます。

ONTAP ツールでは、すべての仮想ボリューム（ VVol ）データストアを新しいストレージ機能プロファイルで設定できます。これにより、同じ VVol データストアに IOPS 要件が異なる複数の仮想マシンをプロビジョニングすることができます。IOPS の要件がある VM のプロビジョニングワークフローを実行する際には、互換性があるデータストアのリストにすべての vVol データストアが表示されます。



== ストレージ機能プロファイルの作成と編集に関する考慮事項

ストレージ機能プロファイルの作成と編集に関する考慮事項を確認しておく必要があります。

* 最小 IOPS は AFF システムでのみ設定できます。
* QoS 指標は仮想ボリューム（ VVol ）データストアレベルで設定できます。
+
この機能により、仮想データストア上にプロビジョニングされた同じ仮想マシンの異なる VMDK に対して、さまざまな QoS 指標をより柔軟に割り当てることが可能です。

* フラッシュアレイハイブリッド、ASA、およびAFFデータストアのストレージ機能プロファイルを設定できます。
+
フラッシュアレイハイブリッド、ASA、AFFの各システムでは、スペースリザベーションをシックまたはシンに設定できます。

* ストレージ機能プロファイルを使用してデータストアの暗号化を行うことができます。
* 以前のバージョンの VMware vSphere 用 ONTAP ツールを最新バージョンの ONTAP ツールにアップグレードしたあとで、既存のストレージ機能プロファイル（ 7.2 より前のバージョンで作成）を変更することはできません。
+
以前のストレージ機能プロファイルは、下位互換性を確保するために保持されます。デフォルトテンプレートが使用されない場合は、最新バージョンの ONTAP ツールへのアップグレード時に、ストレージ機能プロファイルのパフォーマンスに関連する新しい QoS 指標と階層化ポリシーを反映して既存のテンプレートが上書きされます。

* 以前のストレージ機能プロファイルを変更または使用して、新しい仮想データストアや VM ストレージポリシーをプロビジョニングすることはできません。

