---
permalink: configure/concept_considerations_for_creating_and_editing_storage_capability_profiles.html 
sidebar: sidebar 
keywords:  
summary: ストレージ機能プロファイルの作成と編集に関する考慮事項を確認しておく必要があります。 
---
= ストレージ機能プロファイルの作成と編集に関する考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ機能プロファイルの作成と編集に関する考慮事項を次に示します。

* 最小 IOPS は AFF システムでのみ設定できます。
* QoS 指標は仮想ボリューム（ VVol ）データストアレベルで設定できます。
+
この機能により、仮想データストア上にプロビジョニングされた同じ仮想マシンの異なる VMDK に対して、さまざまな QoS 指標をより柔軟に割り当てることが可能です。

* フラッシュアレイハイブリッド、ASA、およびAFFデータストアのストレージ機能プロファイルを設定できます。
+
フラッシュアレイハイブリッドシステム、ASA、AFFシステムでは、スペースリザベーションをシックまたはシンに設定できます。

* ストレージ機能プロファイルを使用してデータストアの暗号化を行うことができます。
* 以前のバージョンの VMware vSphere 用 ONTAP ツールを最新バージョンの ONTAP ツールにアップグレードしたあとで、既存のストレージ機能プロファイル（ 7.2 より前のバージョンで作成）を変更することはできません。
+
以前のストレージ機能プロファイルは、下位互換性を確保するために保持されます。デフォルトテンプレートが使用されない場合は、最新バージョンの ONTAP ツールへのアップグレード時に、ストレージ機能プロファイルのパフォーマンスに関連する新しい QoS 指標を反映して既存のテンプレートが上書きされます。

* 以前のストレージ機能プロファイルを変更または使用して、新しい仮想データストアや VM ストレージポリシーをプロビジョニングすることはできません。

