---
permalink: configure/reference_rebalance_vvols_datastore.html 
sidebar: sidebar 
keywords: vVols datastore,rebalancing 
summary: ONTAP ツールは、データセンター内の FlexVol ボリュームのリバランシングコマンドをサポートします。主な目的は、 FlexVol ボリューム間でスペースを均等に利用できるようにすることです。ONTAP ツールは、スペース使用量、シンプロビジョニング、 LUN 数、およびストレージ機能プロファイルに基づいて、既存のボリュームに VVOL を再配分します。 
---
= VVol データストアのリバランシング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ツールは、データセンター内の FlexVol ボリュームのリバランシングコマンドをサポートします。主な目的は、 FlexVol ボリューム間でスペースを均等に利用できるようにすることです。ONTAP ツールは、スペース使用量、シンプロビジョニング、 LUN 数、およびストレージ機能プロファイルに基づいて、既存のボリュームに VVOL を再配分します。

VVOL データストアのリバランシングは、 LUN の移動またはファイルの移動によって実行されます。VVOLのリバランシングで考慮される基準は次のとおりです。

* NFS VVOLデータストアはサポートされません
* 既存の FlexVol ボリュームのサイズは変更されず、新しい FlexVol ボリュームは追加されません
* 負荷を再分散するのは、ストレージ機能またはボリューム属性が同じ FlexVol ボリュームだけです
* スペース使用量が最も多い FlexVol ボリュームがリバランシングの対象となります
* 仮想マシンに関連付けられているすべての vVol が同じ FlexVol ボリュームに移動されます
* LUN とファイルの数の上限は保持されます
* FlexVol ボリュームのスペース使用率の差が 10% の場合、リバランシングは実行されません


rebalance コマンドは、空の FlexVol を削除して他のデータストアにスペースを提供します。したがって、コマンドを使用すると、不要な FlexVol を削除してデータストアから削除できます。このコマンドでは、仮想マシンに関連付けられているすべての VVOL を同じ FlexVol ボリュームに移動します。問題を最小限に抑えるために、リバランシングが開始される前にコマンドによって事前確認が実行されます。ただし、事前確認が成功した場合でも、 1 つ以上の vVol に対してリバランシング処理が失敗する可能性があります。この場合、再バランス操作はロールバックされません。そのため、仮想マシンに関連付けられた vVol が別の FlexVol ボリュームに配置されている場合、警告ログが生成されることがあります。

[NOTE]
====
* データストアと仮想マシンの並行処理はサポートされていません。
* すべての vVol のリバランシング処理が完了したら、クラスタの再検出処理を実行する必要があります。
* vVol のリバランシング処理で多数の vVol データストアが特定された場合、設定されているデフォルト値を超えると転送処理はタイムアウトします。
+
** その場合は、「 vvol.properties` 」ファイルを変更して値を「 offtap.operation.timeout.period.seconds=29700` 」に設定し、 VASA Provider サービスを再起動してください。


* FlexVol ボリュームに Snapshot がある場合、 vVol のリバランシング処理中に、スペース使用率の詳細が十分でないために vVol が正しくリバランシングされません。
* VASA Providerのproperty_enable.update.vvol.through.discovery_をtrueに設定すると、コンテナのリバランシング処理でタイムアウトが発生したときにONTAP tools for VMware vSphereとONTAP間で整合性のあるデータを取得できます。
* VVolデータストアのリバランシングを行うREST APIは公開されていません。


====
.* 始める前に *
* メンテナンスコンソールからWeb-CLIトークンを生成します。
+
.. maintコンソールにログインします。
.. オプション* 1 *アプライアンス構成を選択します。
.. オプション* 12 * Generate Web-CLI Authentication tokenを選択します。


* vCenterまたはWeb-CLIからコンテナ名とFlexVol Volume名を取得します。
コンテナに接続されているFlexVol Volumeのリストを取得するには、Web CLIからcommand_container list_を実行します。container rebalanceコマンドの詳細については、Web-CLIページを参照してください。



NOTE: コンテナに接続されているすべてのFlexVolボリュームでリバランシングを実行するには、コンテナ名を指定する必要があります。ただし、FlexVolボリュームパラメータを指定した場合、リバランシングは指定したFlexVolボリューム間でのみ実行されます。

.* 手順 *
. URLを使用したWeb-CLIからのログイン `\https://<OTV-IP>:9083/`
. 次のコマンドを実行します。_container rebalance -container_name =<container-name>_

