---
permalink: configure/reference_set_ipv4_or_ipv6.html 
sidebar: sidebar 
keywords:  
summary: プリファレンスファイル kaminoprefs.xml に新しいオプションが追加されました。 VSC に追加されるすべてのストレージシステムで IPv4 または IPv6 のサポートを有効にするように設定できます。 
---
= プリファレンスファイルを使用して IPv4 または IPv6 を設定してください
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プリファレンスファイルには、 VMware vSphere の処理用の ONTAP ツールを制御する設定が含まれています。ほとんどの場合、これらのファイルの設定を変更する必要はありません。Virtual Storage Console （ VSC ）で使用されるプリファレンスファイルを把握しておくと役立ちます。

VSC には複数のプリファレンスファイルがあります。これらのファイルには、 VSC によるさまざまな処理の実行方法を決定するエントリキーと値が含まれています。VSC で使用される一部のプリファレンスファイルを次に示します。

/opt/netapp/vscserver/etc/kamino/kaminoprefs.xml が含まれています

「 /opt/NetApp/vscserver /etc/vsc/vscPreferences.xml 」を参照してください

状況によっては、プリファレンスファイルの変更が必要になることがあります。たとえば、 iSCSI または NFS を使用していて、 ESXi ホストとストレージシステムとでサブネットが異なる場合は、のプリファレンスファイルを変更する必要があります。プリファレンスファイルの設定を変更しないと、 VSC でデータストアをマウントできないためにデータストアのプロビジョニングが失敗します。

プリファレンスファイル「 kaminoprefs.xml 」に新しいオプションが追加されました。 VSC に追加されるすべてのストレージシステムで IPv4 または IPv6 のサポートを有効にするように設定できます。

* 「 efault.override.option.provision.mount.datastore.address.family` 」パラメータが「 kaminoprefs.xml 」プリファレンスファイルに追加され、データストアプロビジョニング用の優先データ LIF プロトコルが設定されました。
+
このプリファレンスは、 VSC に追加されるすべてのストレージシステムに適用されます。

* 新しいオプションの値は 'ipv4'ipv6' および 'none' です
* デフォルトでは、値は「 NONE 」に設定されています。


|===


| * 値 * | * 概要 * 


 a| 
なし
 a| 
* プロビジョニングの際、クラスタ管理 LIF または SVM 管理 LIF と同じ IPv6 または IPv4 アドレスタイプのデータ LIF を使用してストレージが追加されます。
* SVM に同じ IPv6 または IPv4 アドレスタイプのデータ LIF がない場合は、他のタイプのデータ LIF があればプロビジョニングが実行されます。




 a| 
IPv4
 a| 
* 選択した SVM 内の IPv4 データ LIF を使用してプロビジョニングが実行されます。
* SVM に IPv4 データ LIF がない場合、 SVM で使用可能な IPv6 のデータ LIF があれば、プロビジョニングはそのデータ LIF を使用して行われます。




 a| 
IPv6
 a| 
* 選択した SVM 内の IPv6 データ LIF を使用してプロビジョニングが実行されます。
* SVM に IPv6 データ LIF がない場合、 SVM で使用可能な IPv4 のデータ LIF があれば、プロビジョニングは IPv4 のデータ LIF を介して行われます。


|===
ユーザインターフェイスを使用してIPv4またはIPv6を設定するには、次のセクションを参照してください。

* link:../configure/add_different_subnets.html["別のサブネットを追加してください"]
* link:../configure/task_enable_datastore_mounting_across_different_subnets.html["異なるサブネット間でのデータストアのマウントを有効にする"]

