---
permalink: configure/task_provision_vvols_datastores.html 
sidebar: sidebar 
keywords:  
summary: データストアのプロビジョニングウィザードを使用して VVOL データストアをプロビジョニングできるのは、 ONTAP ツールで VASA Provider が有効になっている場合のみです。 
---
= vVol データストアをプロビジョニングする
:icons: font
:imagesdir: ../media/


[role="lead"]
データストアのプロビジョニングウィザードを使用して VVOL データストアをプロビジョニングできるのは、 ONTAP ツールで VASA Provider が有効になっている場合のみです。

* 必要なもの *

* ESXi ホストの接続先のすべてのネットワークのサブネットの詳細が kaminoprefs.xml に入力されていることを確認する必要があります。
+
各種サブネット間でのデータストアのマウントの有効化 * のセクションを参照してください。

* 逆方向のレプリケーションが成功するように、ソースサイトとターゲットサイトの両方のデータストアで同様のレプリケーションポリシーとスケジュールを設定する必要があります。


データストアのプロビジョニングメニューでは、データストアのストレージ機能プロファイルを指定できます。これにより、一貫した Service Level Objectives （ SLO ；サービスレベル目標）を確保し、プロビジョニングプロセスを簡易化できます。ストレージ機能プロファイルは VASA Provider が有効な場合にのみ指定できます。

バッキングストレージとして使用する FlexVol ボリュームは、 ONTAP 9.5 以降を実行している場合にのみ vVol ダッシュボードに表示されます。VVOL データストアのプロビジョニングには、 vCenter Server の新しいデータストアウィザードを使用しないでください。

* VVol データストアを作成するときは、クラスタのクレデンシャルを使用する必要があり
+
SVM のクレデンシャルを使用して vVol データストアを作成することはできません

* VASA Provider では、あるプロトコルを使用する VVol データストアでホストされている仮想マシンを別のプロトコルを使用するデータストアにクローニングすることはできません。
* ソースサイトとデスティネーションサイトの両方でクラスタのペアリングと SVM のペアリングを完了しておく必要があります。


* このタスクについて *


NOTE: 9.10 リリースの ONTAP ツールでは、 All SAN Array （ ASA ）タイプの ONTAP 9.9.1 以降のストレージプラットフォームで、 vmdk サイズが 16TB を超える VVOL データストアを作成できます。

* 手順 *

. vSphere Client のホームページで、 * Hosts and Clusters * をクリックします。
. ナビゲーションペインで、データストアをプロビジョニングするデータセンターを選択します。
. データストアのマウント先のホストを指定します。
+
|===


| * データストアの可用性レベル * | * これをしなさい ...* 


 a| 
データセンター内のすべてのホスト
 a| 
データセンターを右クリックし、 * NetApp VSC * > * Provision Datastore * を選択します。



 a| 
クラスタ内のすべてのホスト
 a| 
クラスタを右クリックし、 * NetApp VSC * > * Provision Datastore * を選択します。



 a| 
単一のホスト
 a| 
ホストを右クリックし、 * NetApp VSC * > * Provision Datastore * を選択します。

|===
. データストアを作成するには、新しいデータストアダイアログボックスのフィールドに情報を入力します。
+
ダイアログボックス内のフィールドのほとんどはわかりやすいもので、説明を必要としません。以下は、説明が必要な一部のフィールドのリストです。

+
|===


| * セクション * | * 概要 * 


 a| 
全般
 a| 
新しいデータストアダイアログボックスの全般セクションには、新しいデータストアの場所、名前、概要、タイプ、およびプロトコルを入力するオプションがあります。vVol データストアの設定には vVol データストアタイプを使用します。


NOTE: VVOL レプリケーション用の iSCSI VVOL データストアをプロビジョニングする場合は、ターゲットサイトで VVOL データストアを作成する前に、 SnapMirror の更新とクラスタの再検出を実行する必要があります。



 a| 
ストレージシステム
 a| 
このセクションでは、 VVOL データストアでレプリケーションを有効にするか無効にするかを選択できます。このリリースでは、非同期タイプのレプリケーションプロファイルのみが許可されています。表示されたストレージ機能プロファイルを 1 つ以上選択できます。ペアリングされている * ストレージシステム * および * Storage VM * の推奨値が自動的に設定されます。推奨値は、 ONTAP でペアリングされている場合にのみ設定されます。これらの値は必要に応じて変更できます。

* 注： * ONTAP で FlexVol ボリュームを作成する際には、ストレージ機能プロファイルで選択する属性を使用してボリュームを作成する必要があります。読み取り / 書き込みの FlexVol ボリュームとデータ保護 LUN の属性は、どちらもほぼ同じでなければなりません。

FlexVol ボリュームを作成し、 ONTAP で SnapMirror を初期化したら、 VSC でストレージを再検出して新しいボリュームを認識できるようにする必要があります。



 a| 
ストレージ属性
 a| 
SnapMirror のスケジュールと、既存のリストから必要な FlexVol のスケジュールを選択します。このスケジュールは、 [VM ストレージポリシー ] ページで選択したスケジュールと同様のものにする必要があります。このユーザは、 SnapMirror を使用する ONTAP で、表示されている FlexVol ボリュームを作成しておく必要があります。VVol の作成に使用するデフォルトのストレージ機能プロファイルを選択するには、 * default storage capability profile * オプションを使用します。デフォルトでは、すべてのボリュームの自動拡張時の最大サイズは 120% に設定されており、これらのボリュームではデフォルトの Snapshot が有効になっています。

* 注： *

** VVOL データストアに含まれる FlexVol ボリュームは、既存のサイズよりも縮小することはできませんが、最大 120% まで拡張できます。この FlexVol ボリュームではデフォルトの Snapshot が有効になっています。
** 作成する FlexVol ボリュームの最小サイズは 5GB です。


|===
. Summary セクションで、 ** Finish ** をクリックします。


* 結果 *

VVOL データストアの設定時にバックエンドでレプリケーショングループが作成されます。

* 関連情報 *

link:../manage/task_monitor_vvols_datastores_and_virtual_machines_using_vvols_dashboard.html["vVol ダッシュボードを使用してパフォーマンスデータを分析します"]
