---
permalink: configure/task_provision_datastores.html 
sidebar: sidebar 
keywords:  
summary: データストアをプロビジョニングすると、仮想マシンとその仮想マシンディスク用の論理コンテナ（ VMDK ）が作成されます。データストアをプロビジョニングし、 1 台のホスト、クラスタ内のすべてのホスト、またはデータセンター内のすべてのホストに接続できます。 
---
= 従来のデータストアをプロビジョニングする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データストアをプロビジョニングすると、仮想マシンとその仮想マシンディスク（ VMDK ）用の論理コンテナが作成されます。データストアをプロビジョニングし、 1 台のホスト、クラスタ内のすべてのホスト、またはデータセンター内のすべてのホストに接続できます。

* 必要なもの *

* Virtual Storage Console （ VSC ）に直接接続された SVM にデータストアをプロビジョニングする場合は、デフォルトの vsadmin ユーザアカウントまたは vsadmin ロールではなく、適切な権限を持つユーザアカウントを使用して SVM を VSC に追加しておく必要があります。
+
クラスタを追加してデータストアをプロビジョニングすることもできます。

* ESXi ホストが接続されているすべてのネットワークのサブネットの詳細が kaminoprefs.xml に入力されていることを確認する必要があります。
+
「異なるサブネット間でのデータストアのマウントの有効化」を参照してください。

* NFS または iSCSI を使用していて、 ESXi ホストとストレージシステムでサブネットが異なる場合は、 kaminoprefs のプリファレンスファイルの NFS または iSCSI の設定に ESXi ホストのサブネットマスクが含まれている必要があります。
+
このプリファレンスファイルは vVol データストアの作成時にも当てはまります。詳細については、「異なるサブネット間でのデータストアのマウントの有効化」および「 VSC プリファレンスファイルの設定」を参照してください。

* VASA Provider が有効な状態で、 NFS データストアまたは VMFS データストアのストレージ機能プロファイルを指定する場合は、 1 つ以上のストレージ機能プロファイルを作成しておく必要があります。
* NFSv4.1 データストアを作成する場合は、 SVM レベルで NFSv4.1 を有効にしておく必要があります。


* Provision Datastore * オプションを使用すると、データストアのストレージ機能プロファイルを指定できます。ストレージ機能プロファイルを使用すると、一貫した Service Level Objectives （ SLO ；サービスレベル目標）を確保し、プロビジョニングプロセスを簡易化できます。ストレージ機能プロファイルは VASA Provider が有効な場合にのみ指定できます。VMware vSphere 用の ONTAP ツールは、次のプロトコルをサポートしています。

* NFSv3 および NFSv4.1
* VMFS5 および VMFS6


データストアは、 NFS ボリュームまたは LUN 上に作成されます。

* NFS データストアの場合、ストレージシステム上に NFS ボリュームが作成され、エクスポートポリシーが更新されます。
* VMFS データストアの場合、新しいボリュームが作成され（既存のボリュームの使用を選択した場合は既存のボリュームが使用される）、 LUN および igroup が作成されます。


[NOTE]
====
* ONTAP ツールでは、 ASA および ONTAP 9.8 以降を実行する承認済みの AFF システムで使用する場合、 VMFS5 および VMFS6 のデータストアのプロビジョニングがサポートされます。最大 VMFS LUN およびボリュームサイズは 64TB です。
+
他のプラットフォームでサポートされる LUN の最大サイズは 16TB です。

* VMware では、データストアクラスタに対して NFSv4.1 がサポートされません。


====
プロビジョニング時にストレージ機能プロファイルを指定しなかった場合は、あとでストレージマッピングページを使用してデータストアをストレージ機能プロファイルにマッピングできます。FlexGroup ベースのデータストアにプロビジョニングされた仮想マシンのデータ VMDK ファイルには、ストレージ QoS 設定、スループットの上限（最大 IOPS ）、およびスループットの下限（最小 IOPS ）を適用できます。QoS 設定は、データストアレベルまたはデータストアを右クリックして個々の仮想マシンレベルで適用できます。右クリックオプションは、 FlexGroup データストアを使用するデータストアまたは仮想マシンでのみ使用できます。データストアに QoS を適用すると、既存のデータストアまたは仮想マシンの QoS 設定よりも優先されます。ONTAP は SVM 管理レベルの QoS をサポートしていないため、 QoS 設定をデータストアレベルまたは直接の SVM でプロビジョニングされたデータストアの仮想マシンレベルで適用することはできません。

* 手順 *

. データストアプロビジョニングウィザードには次のいずれかからアクセスできます。
+
|===


| * から * を選択した場合 | * 次の手順を実行します。 * 


 a| 
vSphere Client のホームページ
 a| 
.. [*Hosts and Clusters*] をクリックします。
.. ナビゲーションペインで、データストアをプロビジョニングするデータセンターを選択します。
.. データストアをマウントするホストを指定するには、次の手順を参照してください。




 a| 
ONTAP ツールのホームページ
 a| 
.. [* 概要 *] をクリックします。
.. [* はじめに * ] タブをクリックします。
.. [* Provision （プロビジョン） ] ボタンをクリックします
.. Browse （参照） * をクリックして、次の手順に従ってデータストアをプロビジョニングするデスティネーションを選択します。


|===
. データストアのマウント先のホストを指定します。
+
|===


| * データストアの可用性レベル * | * これをしなさい ...* 


 a| 
データセンター内のすべてのホスト
 a| 
データセンターを右クリックし、 * NetApp ONTAP tools * > * Provision Datastore * を選択します。



 a| 
クラスタ内のすべてのホスト
 a| 
ホストクラスタを右クリックし、 * NetApp ONTAP tools * > * Provision Datastore * を選択します。



 a| 
単一のホスト
 a| 
ホストを右クリックし、 * NetApp ONTAP tools * > * Provision Datastore * を選択します。

|===
. データストアを作成するには、新しいデータストアダイアログボックスのフィールドに情報を入力します。
+
ダイアログボックス内のフィールドのほとんどはわかりやすいもので、説明を必要としません。以下は、説明が必要な一部のフィールドのリストです。

+
|===


| * セクション * | * 概要 * 


 a| 
全般
 a| 
[New Datastore provisioning （データストアの新規プロビジョニング） ] ダイアログボックスの [General] （全般）セクションには、新しいデータストアのデスティネーション、名前、サイズ、タイプ、およびプロトコルを入力するオプションがあります。NFS * または * VMFS * プロトコルを選択すると、従来のデータストアを設定できます。このリリースでは、最大サイズ 64TB の VMFS データストアを設定できます。「 ONTAP クラスタ全体にわたるデータストアデータ」オプションを選択して、ストレージシステム上で FlexGroup ボリュームをプロビジョニングできます。このオプションを選択すると ' プロビジョニングにストレージ機能プロファイルを使用するチェックボックスが自動的に選択解除されますFlexGroup データストアのプロビジョニングの場合は、 9.8 以降の ONTAP クラスタのみが選択対象として表示されます。vVol データストアの設定には vVol データストアタイプを使用します。VASA Provider が有効になっている場合は、ストレージ機能プロファイルを使用するかどうかも指定できます。* Datastore cluster * オプションは、従来のデータストアに対してのみ使用できます。「 * Advanced * 」オプションを使用して、 * VMFS5 * または * VMFS6 * ファイルシステムを指定する必要があります。



 a| 
ストレージシステム
 a| 
「全般」セクションでオプションを選択した場合は、リストされているストレージ機能プロファイルのいずれかを選択できます。FlexGroup データストアをプロビジョニングする場合、このデータストアのストレージ機能プロファイルはサポートされていません。ストレージシステムと Storage Virtual Machine に対する推奨設定があらかじめ選択されています。ただし、必要に応じて値を変更できます。



 a| 
ストレージ属性
 a| 
アグリゲート * オプションとボリューム * オプションには、デフォルトで推奨値が設定されます。これらの値は要件に応じてカスタマイズが可能です。アグリゲートの選択は ONTAP で管理されるため、 FlexGroup データストアではアグリゲートの選択はサポートされません。「 * 詳細設定 * 」メニューの「 * スペースリザーブ * 」オプションにも最適な結果が得られます。



 a| 
まとめ
 a| 
新しいデータストアについて指定したパラメータの概要を確認できます。Summary （サマリ）ページには、作成したデータストアのタイプを区別するための新しいフィールド「 Volume Style 」が用意されています。「ボリューム・スタイル」には、「 FlexVol 」または「 FlexGroup 」を指定できます。

|===



NOTE: 従来のデータストアに含まれる FlexGroup を既存のサイズよりも縮小することはできませんが、最大 120% まで拡張できます。これらの FlexGroup ボリュームでは、デフォルトの Snapshot が有効になっています。。[ 概要 ] セクションで、 [ * 完了 ] をクリックします。

* 関連情報 *

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Virtual_Storage_Console_for_VMware_vSphere/Datastore_inaccessible_when_volume_status_is_changed_to_offline["ボリュームステータスがオフラインになるとデータストアにアクセスできなくなります"]
