---
permalink: configure/task_configure_user_role_and_privileges.html 
sidebar: sidebar 
keywords: user roles 
summary: ONTAP tools for VMware vSphereおよびONTAP System Managerに付属のJSONファイルを使用して、ストレージシステムの管理に使用する新しいユーザロールを設定できます。 
---
= ユーザロールと権限を設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphereおよびONTAP System Managerに付属のJSONファイルを使用して、ストレージシステムの管理に使用する新しいユーザロールを設定できます。

* 必要なもの *

* 次の手順に従って、ONTAP PrivilegesファイルをONTAP toolsからダウンロードしておく必要があります。
+
** に移動します `\https://{virtual_appliance_IP}:9083/vsc/config/`
** VSC_ONTAP_User_Privileges.zipファイルをダウンロードします。
** ダウンロードしたVSC_ONTAP_User_Privileges.zipファイルを展開します。
** System Managerにアクセスします
+
技術情報アーティクル- https://kb.netapp.com/mgmt/OTV/Virtual_Storage_Console/Virtual_Storage_Console%3A_How_to_retrieve_the_JSON_file_to_configure_user_roles_and_privileges["Virtual Storage Console：ユーザロールと権限を設定するためのJSONファイルの取得方法"] Web-CLIからONTAP Privilegesファイルをダウンロードする方法については、を参照してください。



* ONTAP 9.8P1 以降のストレージを設定しておく必要があります。
* ストレージシステムの管理者権限でログインしている必要があります。


* 手順 *

. ダウンロードした「 \https://{virtual_appliance_IP}:9083/vsc/config/VSC_ONTAP_User_Privileges.zip` 」ファイルを解凍します。
. ONTAP システムマネージャにアクセスします。
. クラスター * > * 設定 * > * ユーザーと役割 * をクリックします。
. [ ユーザーの追加 ] をクリックします。
. [ ユーザーの追加 ] ダイアログボックスで、 [ 仮想化製品 ] を選択します。
. [* Browse] をクリックして、 ONTAP 権限 JSON ファイルを選択し、アップロードします。
+
プロダクトフィールドには、自動的に値が入力されます。

. 製品機能ドロップダウンメニューから必要な機能を選択します。
+
[ * 役割 * （ * role * ） ] フィールドは、選択したプロダクト機能に基づいて自動的に入力されます。

. 必要なユーザ名とパスワードを入力します。
. ユーザに必要な権限（ Discovery 、 Create Storage 、 Modify Storage 、 Destroy Storage ）を選択し、 * Add * をクリックします。


新しいロールとユーザが追加され、設定したロールの詳細な権限が表示されます。


NOTE: アンインストール処理では、ONTAP toolsのロールは削除されませんが、ONTAP tools固有の権限のローカライズされた名前は削除され、「XXX missing privilege」にプレフィックスが追加されます。これは、 vCenter Server に権限を削除するオプションがないためです。ONTAP toolsを再インストールするか、新しいバージョンのONTAP toolsにアップグレードすると、標準のONTAP toolsロールとONTAP tools固有の権限がすべてリストアされます。
