---
permalink: configure/task_provision_datastores.html 
sidebar: sidebar 
keywords:  
summary: データストアをプロビジョニングすると、仮想マシンとその仮想マシンディスク用の論理コンテナ（ VMDK ）が作成されます。データストアをプロビジョニングし、 1 台のホスト、クラスタ内のすべてのホスト、またはデータセンター内のすべてのホストに接続できます。 
---
= 従来のデータストアをプロビジョニングする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データストアをプロビジョニングすると、仮想マシンとその仮想マシンディスク（ VMDK ）用の論理コンテナが作成されます。データストアをプロビジョニングし、 1 台のホスト、クラスタ内のすべてのホスト、またはデータセンター内のすべてのホストに接続できます。

* 必要なもの *

* ONTAP toolsに直接接続されたSVMにデータストアをプロビジョニングする場合は、デフォルトのvsadminユーザアカウントまたはvsadminロールではなく、適切な権限を持つユーザアカウントを使用してSVMをONTAP toolsに追加しておく必要があります。
+
クラスタを追加してデータストアをプロビジョニングすることもできます。

* ESXi ホストが接続されているすべてのネットワークのサブネットの詳細が kaminoprefs.xml に入力されていることを確認する必要があります。
+
「異なるサブネット間でのデータストアのマウントの有効化」を参照してください。

* NFS または iSCSI を使用していて、 ESXi ホストとストレージシステムでサブネットが異なる場合は、 kaminoprefs のプリファレンスファイルの NFS または iSCSI の設定に ESXi ホストのサブネットマスクが含まれている必要があります。
+
このプリファレンスファイルは vVol データストアの作成時にも当てはまります。詳細については、「異なるサブネット間でのデータストアのマウントの有効化」および「ONTAP toolsのプリファレンスファイルの設定」を参照してください。

* VASA Provider が有効な状態で、 NFS データストアまたは VMFS データストアのストレージ機能プロファイルを指定する場合は、 1 つ以上のストレージ機能プロファイルを作成しておく必要があります。
* NFSv4.1 データストアを作成する場合は、 SVM レベルで NFSv4.1 を有効にしておく必要があります。


* Provision Datastore * オプションを使用すると、データストアのストレージ機能プロファイルを指定できます。ストレージ機能プロファイルを使用すると、一貫した Service Level Objectives （ SLO ；サービスレベル目標）を確保し、プロビジョニングプロセスを簡易化できます。ストレージ機能プロファイルは VASA Provider が有効な場合にのみ指定できます。VMware vSphere 用の ONTAP ツールは、次のプロトコルをサポートしています。

* NFSv3 および NFSv4.1
* VMFS5 および VMFS6
* vSphere 8.0リリース以降では、NVMe/FCプロトコルがサポートされます。


ONTAP toolsでは、NFSボリュームまたはLUN上にデータストアを作成できます。

* NFSデータストアの場合、ONTAP toolsはストレージシステム上にNFSボリュームを作成し、エクスポートポリシーを更新します。
* VMFSデータストアの場合、ONTAP toolsは新しいボリュームを作成し（既存のボリュームを使用するオプションを選択した場合は既存のボリュームを使用）、LUNおよびigroupを作成します。


[NOTE]
====
* ONTAP ツールでは、 ASA および ONTAP 9.8 以降を実行する承認済みの AFF システムで使用する場合、 VMFS5 および VMFS6 のデータストアのプロビジョニングがサポートされます。最大 VMFS LUN およびボリュームサイズは 64TB です。
+
他のプラットフォームでサポートされる LUN の最大サイズは 16TB です。

* VMware では、データストアクラスタに対して NFSv4.1 がサポートされません。


====
* Kerberos認証を使用する場合は、次のものが必要です。
+
** Active Directory（AD）を使用したWindowsマシン
** ドメインネームサーバ（DNS）
** キー配布センター（KDC）
** Kerberosが設定されたONTAP ストレージシステム（クラスタ
** Kerberosが設定されたESXiホスト




プロビジョニング時にストレージ機能プロファイルを指定しなかった場合は、あとでストレージマッピングページを使用してデータストアをストレージ機能プロファイルにマッピングできます。FlexGroup ベースのデータストアにプロビジョニングされた仮想マシンのデータ VMDK ファイルには、ストレージ QoS 設定、スループットの上限（最大 IOPS ）、およびスループットの下限（最小 IOPS ）を適用できます。QoS 設定は、データストアレベルまたはデータストアを右クリックして個々の仮想マシンレベルで適用できます。右クリックオプションは、 FlexGroup データストアを使用するデータストアまたは仮想マシンでのみ使用できます。データストアに QoS を適用すると、既存のデータストアまたは仮想マシンの QoS 設定よりも優先されます。ONTAP は SVM 管理レベルの QoS をサポートしていないため、 QoS 設定をデータストアレベルまたは直接の SVM でプロビジョニングされたデータストアの仮想マシンレベルで適用することはできません。

* 手順 *

. データストアプロビジョニングウィザードには次のいずれかからアクセスできます。
+
|===


| * から * を選択した場合 | * 次の手順を実行します。 * 


 a| 
vSphere Client のホームページ
 a| 
.. [*Hosts and Clusters*] をクリックします。
.. ナビゲーションペインで、データストアをプロビジョニングするデータセンターを選択します。
.. データストアをマウントするホストを指定するには、次の手順を参照してください。




 a| 
ONTAP ツールのホームページ
 a| 
.. [* 概要 *] をクリックします。
.. [* はじめに * ] タブをクリックします。
.. [* Provision （プロビジョン） ] ボタンをクリックします
.. Browse （参照） * をクリックして、次の手順に従ってデータストアをプロビジョニングするデスティネーションを選択します。


|===
. データストアのマウント先のホストを指定します。
+
|===


| * データストアの可用性レベル * | * これをしなさい ...* 


 a| 
データセンター内のすべてのホスト
 a| 
データセンターを右クリックし、 * NetApp ONTAP tools * > * Provision Datastore * を選択します。



 a| 
クラスタ内のすべてのホスト
 a| 
ホストクラスタを右クリックし、 * NetApp ONTAP tools * > * Provision Datastore * を選択します。



 a| 
単一のホスト
 a| 
ホストを右クリックし、 * NetApp ONTAP tools * > * Provision Datastore * を選択します。

|===
. データストアを作成するには、新しいデータストアダイアログボックスのフィールドに情報を入力します。
+
ダイアログボックス内のフィールドのほとんどはわかりやすいもので、説明を必要としません。以下は、説明が必要な一部のフィールドのリストです。

+
|===


| * セクション * | * 概要 * 


 a| 
全般
 a| 
[New Datastore provisioning （データストアの新規プロビジョニング） ] ダイアログボックスの [General] （全般）セクションには、新しいデータストアのデスティネーション、名前、サイズ、タイプ、およびプロトコルを入力するオプションがあります。

データストアを設定するには、* NFS *、* VMFS *、または* VVols *のいずれかのタイプを選択します。vVolタイプを選択すると、NVMe/FCプロトコルが使用可能になります。


NOTE: NVMe/FCプロトコルは、ONTAP 9.91P3以降のリリースでサポートされます。

** NFS：NFS3またはNFS4.1プロトコルを使用してNFSデータストアをプロビジョニングできます。
+
[データストアのデータをONTAP クラスタ全体に分散]オプションを選択して、ストレージシステムにFlexGroup ボリュームをプロビジョニングできます。このオプションを選択すると、*[ストレージ機能プロファイルをプロビジョニングに使用する]*チェックボックスが自動的にオフになります。

** VMFS：iSCSIまたはFC / FCoEプロトコルを使用して、ファイルシステムタイプがVMFS5またはVMFS6のVMFSデータストアをプロビジョニングできます。
+

NOTE: VASA Providerが有効になっている場合は、ストレージ機能プロファイルを使用することもできます。





 a| 
Kerberos 認証
 a| 
[*General]ページでNFS 4.1を選択した場合は、セキュリティ・レベルを選択します。

Kerberos認証はFlexVolでのみサポートされます。



 a| 
ストレージシステム
 a| 
「全般」セクションでオプションを選択した場合は、リストされているストレージ機能プロファイルのいずれかを選択できます。

** FlexGroup データストアをプロビジョニングする場合、このデータストアのストレージ機能プロファイルはサポートされていません。ストレージシステムと Storage Virtual Machine に対する推奨設定があらかじめ選択されています。ただし、必要に応じて値を変更できます。
** Kerberos認証の場合、Kerberosで有効になっているストレージシステムが一覧表示されます。




 a| 
ストレージ属性
 a| 
ONTAP toolsの*[アグリゲート]*オプションと*[ボリューム]*オプションには、デフォルトで推奨値が入力されています。これらの値は要件に応じてカスタマイズが可能です。アグリゲートの選択は ONTAP で管理されるため、 FlexGroup データストアではアグリゲートの選択はサポートされません。

「 * 詳細設定 * 」メニューの「 * スペースリザーブ * 」オプションにも最適な結果が得られます。

（オプション）イニシエータグループ名は、「*イニシエータグループ名の変更*」フィールドで指定できます。

** この名前の新しいイニシエータグループがない場合は作成されます。
** 指定したイニシエータグループ名にプロトコル名が追加されます。
** 選択したイニシエータで既存のigroupが見つかった場合は、指定した名前でigroupの名前が変更され、再利用されます。
** igroup名を指定しない場合は、デフォルト名でigroupが作成されます。




 a| 
まとめ
 a| 
新しいデータストアについて指定したパラメータの概要を確認できます。

フィールド「Volume style」を使用すると、作成するデータストアのタイプを区別できます。「ボリューム・スタイル」には、「 FlexVol 」または「 FlexGroup 」を指定できます。

|===
+

NOTE: 従来のデータストアに含まれる FlexGroup を既存のサイズよりも縮小することはできませんが、最大 120% まで拡張できます。これらの FlexGroup ボリュームでは、デフォルトの Snapshot が有効になっています。

. [ 概要 ] セクションで、 [ * 完了 ] をクリックします。


* 関連情報 *

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Virtual_Storage_Console_for_VMware_vSphere/Datastore_inaccessible_when_volume_status_is_changed_to_offline["ボリュームステータスがオフラインになるとデータストアにアクセスできなくなります"]

https://docs.netapp.com/us-en/ontap/nfs-admin/ontap-support-kerberos-concept.html["ONTAP での Kerberos のサポート"]

https://docs.netapp.com/us-en/ontap/nfs-admin/requirements-configuring-kerberos-concept.html["NFS で Kerberos を設定するための要件"]

https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/concept_kerberos_realm_services.html["System Manager - ONTAP 9.7 以前を使用して Kerberos Realm サービスを管理します"]

https://docs.netapp.com/us-en/ontap/nfs-config/create-kerberos-config-task.html["データ LIF で Kerberos を有効にします"]

https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.storage.doc/GUID-BDCB7500-72EC-4B6B-9574-CFAEAF95AE81.html["ESXiホストでKerberos認証を設定"]
