---
permalink: configure/task_assign_qos_policies.html 
sidebar: sidebar 
keywords:  
summary: FlexGroup データストアをプロビジョニングしても、データストアにストレージ機能プロファイルを割り当てることはできません。ただし、 FlexGroup ベースのデータストアに作成された仮想マシンに QoS ポリシーを割り当てることができます。 
---
= QoS ポリシーを割り当てる
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexGroup データストアをプロビジョニングしても、データストアにストレージ機能プロファイルを割り当てることはできません。ただし、 FlexGroup ベースのデータストアに作成された仮想マシンに QoS ポリシーを割り当てることができます。

* このタスクについて *

QoS ポリシーは、仮想マシンレベルまたはデータストアレベルのいずれかで適用できます。QoS ポリシーは、データストアがスループット（最大および最小 IOPS ）しきい値を設定するために必要です。QoS を設定したデータストアは、 FlexGroup ボリュームではなく、データストア上の仮想マシンに適用されます。ただし、データストア内のすべての仮想マシンに対して QoS を設定すると、その仮想マシンに対する個々の QoS 設定が上書きされます。これは、データストアで使用可能な仮想マシンにのみ該当し、移行または追加された仮想マシンには該当しません。特定のデータストアで新たに追加または移行された仮想マシンに QoS を適用する場合は、 QoS 値を手動で設定する必要があります。


NOTE: ONTAP では Storage VM 管理レベルの QoS がサポートされないため、直接接続の Storage VM でプロビジョニングされたデータストアまたは仮想マシンレベルで QoS 設定を適用することはできません。

* 手順 *

. ONTAP ツールのホームページで、 * メニュー * > * ホストおよびクラスタ * をクリックします。
. 必要なデータストアまたは仮想マシンを右クリックし、 * NetApp ONTAP ツール * > * QoS の割り当て * をクリックします。
. Assign QoS （ QoS の割り当て）ダイアログボックスで、必要な IOPS 値を入力し、 * Apply * （適用）をクリックします。

