---
permalink: configure/task_add_storage_systems.html 
sidebar: sidebar 
keywords:  
summary: ONTAP toolsにストレージシステムを手動で追加できます。 
---
= ストレージシステムを追加
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP toolsにストレージシステムを手動で追加できます。


NOTE: ONTAP クラスタでSAMLが有効になっている場合は、ONTAP との通信にベーシック認証が使用されます。

* このタスクについて *

ONTAP toolsを起動するか、*[すべて再検出]*オプションを選択すると、使用可能なストレージシステムがONTAP tools for VMware vSphereによって自動的に検出されます。


NOTE: SVMユーザではVVolデータストアはサポートされません。

* 手順 *

. ONTAP toolsのホームページのいずれかのオプションを使用して、ONTAP toolsにストレージシステムを追加します。
+
** [ * ストレージ・システム * ] > [ * 追加 ] をクリックします。または
** [* 概要 *>] 、 [* はじめに ] の順にクリックし、 [ ストレージシステムの追加 ] の下の [* 追加 ] ボタンをクリックします。


. Add Storage System * （ストレージ・システムの追加）ダイアログ・ボックスで ' そのストレージ・システムの管理 IP アドレスとクレデンシャルを入力します
+
ストレージシステムを追加する場合は、ONTAP toolsプラグインとストレージシステム間の通信を相互認証する必要があります。

+
クラスタまたは SVM の IPv6 アドレスを使用してストレージシステムを追加することもできます。

+
ONTAP toolsの[ストレージシステム]ページからストレージを追加する場合は、ストレージが配置されているvCenter Serverインスタンスを指定します。Add Storage System ダイアログボックスには、使用可能な vCenter Server インスタンスのドロップダウンリストが表示されます。vCenter Serverインスタンスにすでに関連付けられているデータセンターにストレージを追加する場合、ONTAP toolsはこのオプションを表示しません。

+
注

+
** ONTAP tools 9.12以降では、すべてのONTAP ストレージシステムの通信に証明書ベースの認証が使用されます。
** クライアント証明書またはクラスタ証明書が無効な場合、従来のデータストア操作（削除、サイズ変更、マウントなど）は実行できません。
** クライアント証明書またはクラスタ証明書が無効な場合、VVolデータストアの拡張やデータストアのマウントなどの操作は実行できません。
** [削除]、[ストレージの削除]、[プロパティの編集]などのアクションは、ONTAP 通信を必要としないため許可されます。
** SVMを対象としたユーザを使用してストレージシステムを追加するには、ストレージシステムのクラスタ管理者がユーザを編集し、アプリケーションHTTPおよびONTAPIに認証方式*証明書*を追加する必要があります。
+
詳細オプションでは、* ONTAP クラスタ証明書*をアップロードする方法は2つあります。

+
... *自動取得*-証明書を自動的に取得します。
... *手動でアップロード*-証明書がある場所を手動で参照し、証明書をアップロードする必要があります。




. 必要な情報をすべて追加したら、「 * OK 」をクリックします。
+
[Authorize Cluster Certificate]ポップアップが表示されます。

. [証明書の表示]*をクリックすると、証明書の詳細が表示されます。[はい]*をクリックしてストレージシステムを追加します

