---
permalink: configure/task_modify_storage_system.html 
sidebar: sidebar 
keywords:  
summary: 証明書の有効期限が切れたとき、または証明書が手動で変更されたときに、証明書を更新する必要があります。クライアント証明書またはクラスタ証明書の有効期限が切れるか一致しないと、ONTAP システムとの通信が切断されます。 
---
= ストレージシステムを変更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージシステムを変更するには、次の手順 を使用してください。

* 手順 *

. NetApp ONTAP tools *から*[ストレージシステム]*を選択します。
. 証明書を更新するストレージシステム*[使用可能な操作]*（3つの縦のドット）ボタンをクリックします。
. [変更]*を選択します。
+

NOTE: クラスタまたはクライアントの証明書の有効期限が切れる前に、ONTAP から更新した証明書を取得するか、ONTAP tools for VMware vSphereからクライアント証明書を生成することを推奨します。

. [ストレージシステムの変更]ウィンドウの*[証明書のアップロード]*フィールドで、*[参照]*をクリックしてONTAP 証明書が保存されている場所に移動し、証明書をアップロードします。
+
クラスタ証明書の場合：

+
** ONTAP でクラスタ証明書を変更した場合は、変更した証明書をONTAP toolsに手動でアップロードする必要があります。これは必須の手順です。
** クラスタ証明書の有効期限が切れると、ストレージシステムのステータスがクラスタの証明書の有効期限が切れましたに変わります。クラスタ証明書の有効期限が切れたら、ストレージ管理者はONTAP 側で新しい証明書を生成する必要があります。[ストレージシステムの変更]*ウィンドウでは、ONTAP ストレージからクラスタ証明書が自動的に取得され、クラスタ証明書を承認する必要があります。


. クライアント証明書の有効期限が切れると、ストレージシステムのステータスが[Client Certificate Expired]に変わります。
+
クライアント証明書の有効期限が切れている場合は、*[ストレージシステムの変更]*ウィンドウで*[ ONTAP 用の新しいクライアント証明書を生成する]*オプションを選択して証明書を再生成します。



証明書をインストールすると、ONTAP との通信が復元されます。
