---
permalink: configure/task_set_default_credentials_for_storage_systems.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere 用の ONTAP ® ツールを使用して、 vCenter Server でストレージシステムのデフォルトクレデンシャルを設定できます。 
---
= ストレージシステムのデフォルトクレデンシャルを設定
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere 用の ONTAP ® ツールを使用して、 vCenter Server でストレージシステムのデフォルトクレデンシャルを設定できます。

* 必要なもの *

デフォルトクレデンシャルの作成に使用する vCenter Server を選択しておく必要があります。

* このタスクについて *

ストレージシステムのデフォルトクレデンシャルを設定すると、 Virtual Storage Console （ VSC ）ではそれらのクレデンシャルを使用して、 VSC が検出したストレージシステムにログインします。デフォルトクレデンシャルでログインできない場合は、ストレージシステムに手動でログインする必要があります。VSC と SRA は、クラスタレベルまたは SVM レベルでストレージシステムのクレデンシャルの追加をサポートします。ただし、 VASA Provider はクラスタレベルのクレデンシャルとのみ連携します。

* 手順 *

. ONTAP ツールのホームページで、 * 設定 * > * 管理設定 * > * ストレージ・システムのデフォルト・クレデンシャルの設定 * をクリックします。
. ストレージシステムのデフォルトクレデンシャルダイアログボックスで、ストレージシステムのユーザ名とパスワードを入力します。
+
ストレージコントローラのクレデンシャルは、ユーザ名とパスワードのペアに基づいて ONTAP で割り当てられます。ストレージコントローラのクレデンシャルは、管理者アカウントまたはロールベースアクセス制御（ RBAC ）を使用するカスタムアカウントのどちらかです。

+
ストレージコントローラのユーザ名とパスワードのペアに関連付けられているロールを VSC で変更することはできません。ONTAP ツールで使用する新しい ONTAP ユーザロールを変更または作成するには、 System Manager を使用します。

+
VMware ® vSphere 導入およびセットアップガイド（ 9.7 リリース用）の _ ONTAP ® ツールの「ユーザーの役割と権限の設定」セクションを参照してください。

. OK * をクリックして、デフォルトクレデンシャルを保存します。


ストレージ・システムのステータスが「認証エラー」と報告されたためにストレージ・システムのクレデンシャルを更新した場合は、 [ ストレージ・システム ] ページで [ すべて再検出 ] オプションをクリックする必要があります。これにより、新しいクレデンシャルを使用してストレージシステムへの接続が試行されます。
