---
permalink: configure/task_map_storage_to_storage_capability_profiles.html 
sidebar: sidebar 
keywords:  
summary: VASA Provider for ONTAP に関連付けられているデータストアを、ストレージ機能プロファイルにマッピングできます。ストレージ機能プロファイルに関連付けられていないデータストアにプロファイルを割り当てることができます。 
---
= データストアとストレージ機能プロファイルのマッピング
:icons: font
:imagesdir: ../media/


[role="lead"]
VASA Provider for ONTAP に関連付けられているデータストアを、ストレージ機能プロファイルにマッピングできます。ストレージ機能プロファイルに関連付けられていないデータストアにプロファイルを割り当てることができます。

* 必要なもの *

* VASA Provider インスタンスを VMware vSphere 用の ONTAP ® ツールに登録しておく必要があります。
* ストレージが Virtual Storage Console （ VSC ）で検出されている必要があります。


従来のデータストアをストレージ機能プロファイルにマッピングしたり、データストアに関連付けられているストレージ機能プロファイルを変更したりできます。VASA Provider の Storage Mappings ページに、仮想ボリューム（ VVol ）データストアは表示されません。このタスクで使用するデータストアは、すべて従来のデータストアです。

* 手順 *

. ONTAP ツールのホームページで、 * ストレージマッピング * をクリックします。
+
Storage Mapping ページでは、次の情報を確認できます。

+
** データストアに関連付けられている vCenter Server
** データストアに一致するプロファイルの数
+
Storage Mapping ページには、従来のデータストアのみが表示されます。このページには、 VVOL データストアや qtree データストアは表示されません。

** データストアにプロファイルが関連付けられているかどうか
+
データストアが複数のプロファイルに一致することがありますが、関連付けることができるプロファイルは 1 つだけです。

** データストアが関連付けられているプロファイルに準拠しているかどうか


. ストレージ機能プロファイルをデータストアにマッピングしたり、データストアの既存のプロファイルを変更したりするには、データストアを選択します。
+
ストレージマッピングページで特定のデータストアやその他の情報を検索するには、検索ボックスに名前または文字列の一部を入力します。VSC のダイアログボックスに検索結果が表示されます。全体表示に戻るには、検索ボックスからテキストを削除し、 * Enter * をクリックします。

. [ アクション ] メニューから、 [ 一致するプロファイルの割り当て *] を選択します。
. データストアにマッピングするプロファイルを、「データストアへのプロファイルの割り当て * 」ダイアログボックスに表示されている一致するプロファイルのリストから選択し、「 * OK 」をクリックして、選択したプロファイルをデータストアにマッピングします。
. 画面を更新して新しい割り当てを確認します。

