---
permalink: manage/concept_virtual_storage_console_reports.html 
sidebar: sidebar 
keywords:  
summary: ONTAP ツールコンソールのレポートメニューを使用して、特定の vCenter Server の選択した VSC インスタンスで管理されているすべてのデータストアに関する事前定義済みのレポートを表示できます。レポートのソートやエクスポートなどの操作を実行できます。 
---
= ONTAP Tools データストアおよび VVol レポートの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ツールコンソール * レポート * メニューを使用すると、特定の vCenter Server の選択した VSC インスタンスで管理されているすべてのデータストアに関する事前定義済みのレポートを表示できます。レポートのソートやエクスポートなどの操作を実行できます。

レポートには、データストアと仮想マシンに関する詳細情報が表示されます。これにより、 vCenter Server 内のデータストアおよび仮想マシンに関する潜在的な問題を確認して特定できます

レポートの表示、ソート、エクスポートが可能です。

Virtual Storage Console （ VSC ）には、次の事前定義済みのレポートが用意されています。

* データストアレポート
* 仮想マシンレポート
* vVol データストアレポート
* vVol 仮想マシンレポート




== データストアレポート

データストアレポートには、従来のデータストアと、これらのデータストアに作成された仮想マシンに関する詳細情報が表示されます。

従来のダッシュボードを使用すると、 vCenter Server 内のデータストアおよび仮想マシンの潜在的な問題を確認して特定できます。レポートの表示、ソート、エクスポートが可能です。従来のデータストアおよび仮想マシンのレポートデータは、 vCenter Server から提供されます。しかし、 FlexGroup ベースのデータストアがサポートされるようになり、レイテンシ、スループット、 IOPS などの一部の指標が ONTAP から取得されるようになりました。


NOTE: 直接接続の Storage Virtual Machine （ SVM ）に設定された FlexGroup データストアではファイル監視はサポートされていません。

データストアには、次のレポートがあらかじめ定義されています。

* データストアレポート
* 仮想マシンレポート


* データストアレポート *

Datastore Report メニューには、データストアに関する次のパラメータの情報が表示されます。

* データストアの名前
* データストアのタイプ： NFS または VMFS
* ボリュームの形式
+
ボリュームの形式は、 FlexVol または FlexGroup のいずれかです。

* 空きスペース
* 使用済みスペース
* 合計スペース
* 使用済みスペースの割合
* 使用可能なスペースの割合
* IOPS
+
データストアの IOPS が表示されます。

* レイテンシ
+
データストアのレイテンシ情報が表示されます。

+
レポートが生成された時刻を確認することもできます。[ データストアレポート ] メニューでは、要件に応じてレポートを整理し、 [*CSV にエクスポート ] ボタンを使用して整理されたレポートをエクスポートできます。レポート内のデータストア名は、選択したデータストアの Monitor タブに移動するためのリンクで、データストアのパフォーマンス指標を確認できます。



* 仮想マシンレポート *

Virtual Machine Report メニューには、選択した vCenter Server に対して VSC でプロビジョニングされたデータストアを使用するすべての仮想マシンのパフォーマンス指標が表示されます。仮想マシンレポートに表示される仮想マシン指標は履歴データであり、従来のデータストア上の仮想マシンについては 30 分ごとに収集されます。「 Last refresh time 」および「 Next refresh time 」がテーブルに追加され、データが収集された時刻と次のデータ収集のタイミングに関する詳細が提供されます。

* 仮想マシンの名前
* データストア名
* ボリュームの形式
+
ボリュームの形式には、 FlexVol ボリュームと FlexGroup ボリュームのどちらかを指定できます。

* ソース
+
仮想マシンの詳細を収集するソースには、 ONTAP と vCenter Server があります。

* レイテンシ
+
仮想マシンに関連付けられているすべてのデータストアでの仮想マシンのレイテンシが表示されます。

* IOPS
* スループット
* コミット済み容量
+
仮想マシンのコミット済み容量の値が表示されます。

* ホスト
+
仮想マシンを使用できるホストシステムが表示されます。

* アップタイム
+
仮想マシンの電源がオンになり、 ESXi ホストで利用可能になってからの時間が表示されます。

* 電源状態
+
仮想マシンの電源がオンになっているかオフになっているかが表示されます。



レポート内の各仮想マシン名は、選択した仮想マシンの [ モニタ ] タブへのリンクです。仮想マシンのレポートを要件に応じてソートし、 .csv ファイルにエクスポートしてローカルシステムに保存することができます。保存したレポートには、レポートのタイムスタンプも追加されます。

FlexGroup ボリュームをベースとする仮想マシンでは、新しい仮想マシンの電源をオンにすると、 ONTAP で監視するためのファイルが登録されます。レイテンシ、スループット、および IOPS の履歴指標は、 VM レポートに ONTAP からアクセスしたときに取得されます。



== vVol レポート

vVol レポートには、 VMware Virtual Volumes （ vVol ）データストアと、それらのデータストアに作成された仮想マシンに関する詳細情報が表示されます。vVol ダッシュボードを使用すると、 vCenter Server 内の vVol データストアおよび仮想マシンの潜在的な問題を確認して特定できます。

レポートを表示、整理、エクスポートできます。vVol データストアおよび仮想マシンのレポートデータは、 OnCommand API サービスと一緒に ONTAP から提供されます。

vVol には、次の組み込みのレポートが用意されています。

* vVol データストアレポート
* vVol VM レポート


* vVol データストアレポート *

vVol データストアレポートのメニューには、データストアに関する次のパラメータに関する情報が表示されます。

* vVol データストア名
* 空きスペース
* 使用済みスペース
* 合計スペース
* 使用済みスペースの割合
* 使用可能なスペースの割合
* IOPS
* ONTAP 9.8 以降の NFS ベースの VVOL データストアについては、レイテンシのパフォーマンス指標を確認できます。レポートが生成された時刻を確認することもできます。vVol データストアレポートのメニューでは、要件に応じてレポートを整理し、 CSV にエクスポート * ボタンを使用して整理されたレポートをエクスポートできます。レポート内の各 SAN vVol データストア名は、選択した SAN vVol データストアの監視タブに移動するためのリンクで、パフォーマンス指標を表示できます。


* VVol 仮想マシンレポート *

vVol 仮想マシンのサマリレポートのメニューには、選択した vCenter Server 用に VASA Provider for ONTAP でプロビジョニングされた SAN vVol データストアを使用するすべての仮想マシンのパフォーマンス指標が表示されます。VM レポートに表示される仮想マシン指標は履歴データであり、 VVOL データストア上の仮想マシンについては 10 分ごとに収集されます。「最終更新時刻」と「次の更新時刻」が表に追加され、データが収集された時刻と次のデータ収集時刻に関する情報が提供されます。

* 仮想マシンの名前
* コミット済み容量
* アップタイム
* IOPS
* スループット
+
仮想マシンの電源がオンになっているかオフになっているかが表示されます。

* 論理スペース
* ホスト
* 電源状態
* レイテンシ
+
仮想マシンに関連付けられているすべての VVol データストアでの仮想マシンのレイテンシが表示されます。



レポート内の各仮想マシン名は、選択した仮想マシンの [ モニタ ] タブへのリンクです。仮想マシンレポートを要件に応じて整理し、レポートを「 .csv 」形式でエクスポートして、ローカルシステムに保存できます。保存したレポートには、タイムスタンプが追加されます。
