---
permalink: manage/concept_what_vasa_provider_reports_do.html 
sidebar: sidebar 
keywords: VSC, VASA Provider, and SRA 
summary: vVol レポートには、 VMware Virtual Volumes \ （ vVol \ ）データストアと、それらのデータストアに作成された仮想マシンに関する詳細情報が表示されます。vVol ダッシュボードを使用すると、 vCenter Server 内の vVol データストアおよび仮想マシンの潜在的な問題を確認して特定できます。 
---
= vVol レポート
:icons: font
:imagesdir: ../media/


[role="lead"]
vVol レポートには、 VMware Virtual Volumes （ vVol ）データストアと、それらのデータストアに作成された仮想マシンに関する詳細情報が表示されます。vVol ダッシュボードを使用すると、 vCenter Server 内の vVol データストアおよび仮想マシンの潜在的な問題を確認して特定できます。

レポートを表示、整理、エクスポートできます。vVol データストアおよび仮想マシンのレポートデータは、 OnCommand API サービスと一緒に ONTAP から提供されます。

vVol には、次の組み込みのレポートが用意されています。

* vVol データストアレポート
* vVol VM レポート


* vVol データストアレポート *

+ VVol データストアレポートメニューには、データストアに関する次のパラメータに関する情報が表示されます。

* vVol データストア名
* 空きスペース
* 使用済みスペース
* 合計スペース
* 使用済みスペースの割合
* 使用可能なスペースの割合
* IOPS
* ONTAP 9.8 以降の NFS ベースの VVOL データストアについては、レイテンシのパフォーマンス指標を確認できます。レポートが生成された時刻を確認することもできます。vVol データストアレポートのメニューでは、要件に応じてレポートを整理し、 CSV にエクスポート * ボタンを使用して整理されたレポートをエクスポートできます。レポート内の各 SAN vVol データストア名は、選択した SAN vVol データストアの監視タブに移動するためのリンクで、パフォーマンス指標を表示できます。


* VVol 仮想マシンレポート *

+ VVol Virtual Machine Summary Report メニューには、選択した vCenter Server に対して VASA Provider for ONTAP でプロビジョニングされた SAN VVol データストアを使用するすべての仮想マシンのパフォーマンス指標が表示されます。VM レポートに表示される仮想マシン指標は履歴データであり、 VVOL データストア上の仮想マシンについては 10 分ごとに収集されます。「最終更新時刻」と「次の更新時刻」が表に追加され、データが収集された時刻と次のデータ収集時刻に関する情報が提供されます。

* 仮想マシンの名前
* コミット済み容量
* アップタイム
* IOPS
* スループット
+
仮想マシンの電源がオンになっているかオフになっているかが表示されます。

* 論理スペース
* ホスト
* 電源状態
* レイテンシ
+
仮想マシンに関連付けられているすべての VVol データストアでの仮想マシンのレイテンシが表示されます。



レポート内の各仮想マシン名は、選択した仮想マシンの [ モニタ ] タブへのリンクです。仮想マシンのレポートを要件に応じて整理し、レポートを .csv 形式でエクスポートして、ローカルシステムに保存することができます。保存したレポートには、タイムスタンプが追加されます。
