---
permalink: manage/concept_datastore_reports.html 
sidebar: sidebar 
keywords: Datastore Reports 
summary: データストアレポートには、従来のデータストアと、これらのデータストアに作成された仮想マシンに関する詳細情報が表示されます。 
---
= データストアレポート
:icons: font
:imagesdir: ../media/


[role="lead"]
データストアレポートには、従来のデータストアと、これらのデータストアに作成された仮想マシンに関する詳細情報が表示されます。

従来のダッシュボードを使用すると、 vCenter Server 内のデータストアおよび仮想マシンの潜在的な問題を確認して特定できます。レポートの表示、ソート、エクスポートが可能です。従来のデータストアおよび仮想マシンのレポートデータは、 vCenter Server から提供されます。しかし、 FlexGroup ベースのデータストアがサポートされるようになり、レイテンシ、スループット、 IOPS などの一部の指標が ONTAP から取得されるようになりました。


NOTE: 直接接続の Storage Virtual Machine （ SVM ）に設定された FlexGroup データストアではファイル監視はサポートされていません。

データストアには、次のレポートがあらかじめ定義されています。

* データストアレポート
* 仮想マシンレポート


* データストアレポート *

+ Datastore Report メニューには、データストアに関する次のパラメータが表示されます。

* データストアの名前
* データストアのタイプ： NFS または VMFS
* ボリュームの形式
+
ボリュームの形式は、 FlexVol または FlexGroup のいずれかです。

* 空きスペース
* 使用済みスペース
* 合計スペース
* 使用済みスペースの割合
* 使用可能なスペースの割合
* IOPS
+
データストアの IOPS が表示されます。

* レイテンシ
+
データストアのレイテンシ情報が表示されます。

+
レポートが生成された時刻を確認することもできます。[ データストアレポート ] メニューでは、要件に応じてレポートを整理し、 [*CSV にエクスポート ] ボタンを使用して整理されたレポートをエクスポートできます。レポート内のデータストア名は、選択したデータストアの Monitor タブに移動するためのリンクで、データストアのパフォーマンス指標を確認できます。



* 仮想マシンレポート *

+ Virtual Machine Report メニューには、選択した vCenter Server に対して VSC でプロビジョニングされたデータストアを使用するすべての仮想マシンのパフォーマンス指標が表示されます。仮想マシンレポートに表示される仮想マシン指標は履歴データであり、従来のデータストア上の仮想マシンについては 30 分ごとに収集されます。データが収集された時刻と次のデータ収集時刻の詳細を示すために ' 最後の更新時刻と次の更新時刻がテーブルに追加されます

* 仮想マシンの名前
* データストア名
* ボリュームの形式
+
ボリュームの形式には、 FlexVol ボリュームと FlexGroup ボリュームのどちらかを指定できます。

* ソース
+
仮想マシンの詳細を収集するソースには、 ONTAP と vCenter Server があります。

* レイテンシ
+
仮想マシンに関連付けられているすべてのデータストアでの仮想マシンのレイテンシが表示されます。

* IOPS
* スループット
* コミット済み容量
+
仮想マシンのコミット済み容量の値が表示されます。

* ホスト
+
仮想マシンを使用できるホストシステムが表示されます。

* アップタイム
+
仮想マシンの電源がオンになり、 ESXi ホストで利用可能になってからの時間が表示されます。

* 電源状態
+
仮想マシンの電源がオンになっているかオフになっているかが表示されます。



レポート内の各仮想マシン名は、選択した仮想マシンの [ モニタ ] タブへのリンクです。仮想マシンのレポートを要件に応じてソートし、 .csv ファイルにエクスポートしてローカルシステムに保存することができます。保存したレポートには、レポートのタイムスタンプも追加されます。

FlexGroup ボリュームをベースとする仮想マシンでは、新しい仮想マシンの電源をオンにすると、 ONTAP で監視するためのファイルが登録されます。レイテンシ、スループット、および IOPS の履歴指標は、 VM レポートに ONTAP からアクセスしたときに取得されます。
