---
permalink: manage/task_resize_datastores.html 
sidebar: sidebar 
keywords:  
summary: データストアのサイズを変更することで、仮想マシンファイル用のストレージを拡張または縮小できます。データストアのサイズ変更は、インフラ要件の変更に合わせて必要になる場合があります。 
---
= データストアのサイズを変更
:icons: font
:imagesdir: ../media/


[role="lead"]
データストアのサイズを変更することで、仮想マシンファイル用のストレージを拡張または縮小できます。データストアのサイズ変更は、インフラ要件の変更に合わせて必要になる場合があります。

* このタスクについて *

VMFS データストアのサイズ変更時に包含ボリュームのサイズを変更するようにするには、 VMFS データストアの初期プロビジョニング時にストレージ属性セクションの既存のボリュームの使用 * オプションを使用せずに、各データストア用に新しいボリュームを自動的に作成するようにします。

NFS データストアのサイズは拡張または縮小できますが、 VMFS データストアの場合はサイズを拡張することしかできません。データストアのサイズ変更は、自動拡張および縮小オプションが設定された FlexGroup データストアでもサポートされます。VVOL データストアに含まれる従来のデータストアおよび FlexVol ボリュームの一部である FlexGroup は、既存のサイズよりも縮小することはできませんが、最大 120% まで拡張できます。これらの FlexGroup ボリュームと FlexVol ボリュームでは、デフォルトの Snapshot が有効になっています。


NOTE: ONTAP 9.9.1 以降で All SAN Array （ ASA ）タイプのストレージプラットフォームを使用している場合、 16TB を超える VMDK サイズの VVOL データストアのみを作成できます。

* 手順 *

. vSphere Client のホームページで、 * Hosts and Clusters * をクリックします。
. ナビゲーションペインで、データストアが含まれているデータセンターを選択します。
. データストアを右クリックし、 * NetApp ONTAP tools * > * assign QoS * を選択します。
. サイズ変更ダイアログボックスで、データストアの新しいサイズを指定し、 * OK * をクリックします。
+
Storage Systems （ストレージシステム）メニューの * rediscover all * オプションを実行して、 Storage Systems and dashboard （ストレージシステムおよびダッシュボード）のストレージ・リストを手動で更新したり、次のスケジュールされた更新を待機したりできます。


