---
permalink: manage/task_add_storage_to_a_vvol_datastore.html 
sidebar: sidebar 
keywords: virtual volume datastores 
summary: ストレージの追加ウィザードを使用して既存の VMware 仮想ボリューム（ vVol ）データストアに FlexVol ボリュームを追加することで、利用可能なストレージ容量を増やすことができます。 
---
= vVol データストアにストレージを追加する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージの追加ウィザードを使用して既存の VMware 仮想ボリューム（ vVol ）データストアに FlexVol ボリュームを追加することで、利用可能なストレージ容量を増やすことができます。

* このタスクについて *

FlexVol ボリュームを追加する際、そのボリュームに関連付けられるストレージ機能プロファイルを変更することもできます。VASA Provider の自動生成機能を使用してボリュームの新しいプロファイルを作成する方法と、既存のいずれかのプロファイルをボリュームに割り当てる方法があります。

[NOTE]
====
* レプリケーション機能を使用して VVOL データストアを拡張する場合、新しい FlexVol は作成できませんが、設定済みの FlexVol ボリュームだけを既存のリストから選択できます。
* スペース不足が原因で、 VVOL レプリケーションを使用するデータストアに導入されている保護対象の仮想マシンのクローニングが失敗する場合は、 FlexVol のサイズを増やす必要があります。
* AFF クラスタに VVOL データストアを作成した場合、ストレージ機能プロファイルを自動生成する別の FlexVol を使用してデータストアを拡張することはできません。
+
** ストレージ機能プロファイルが事前に作成されている FlexVol を使用して、 VVOL データストアを拡張することができます。




====
* 手順 *

. vSphere Client のホームページで、 * Hosts and Clusters * をクリックします。
. VVOL データストアを右クリックし、 * NetApp ONTAP tools * > * Expand Storage of Vvol Datastore * を選択します。
. vVol データストアのストレージの拡張ページで、既存の FlexVol を vVol データストアに追加するか、データベースに追加する新しい FlexVol を作成することができます。
+
|===


| * を選択した場合 * | * 次の手順を実行します。 * 


 a| 
ボリュームを選択します
 a| 
.. vVol データストアに追加する FlexVol を選択します。
.. ストレージ機能プロファイル列で、ドロップダウンリストを使用して、 FlexVol ボリュームに基づいて新しいプロファイルを作成するか、既存のプロファイルのいずれかを選択します。
+
自動生成機能を使用すると、その FlexVol に関連付けられたストレージ機能に基づいてプロファイルが作成されます。たとえば、ディスクタイプ、高可用性、ディザスタリカバリ、パフォーマンス機能、重複排除などです。





 a| 
新しいボリュームを作成する
 a| 
.. FlexVol の名前、サイズ、およびストレージ機能プロファイルを入力します。
+
選択したストレージ機能プロファイルに基づいて、アグリゲートが選択されます。

.. 「 * Auto grow * 」オプションを選択し、最大サイズを指定します。
.. FlexVol をボリュームのリストに追加するには、 * add * をクリックします。


|===
+
* 注意： VVOL データストアに追加する FlexVol は、すべて同じ Storage Virtual Machine （ SVM 、旧 Vserver ）のものでなければなりません。

+
FlexVol ボリュームを作成したら、 * Modify * ボタンをクリックしてボリュームを編集できます。削除することもできます。

. 仮想マシンの作成時に使用するデフォルトのストレージ機能プロファイルを選択し、 * Next * をクリックして、 VVOL データストアに追加されたストレージの概要を確認します。
. [ 完了 ] をクリックします。


* 結果 *

指定したストレージが vVol データストアに追加されます。処理が完了すると、成功メッセージが表示されます。


NOTE: ESXi ストレージの再スキャンなどの必要な処理は、 vVol データストアのストレージの拡張ウィザードで自動的に実行されます。VVOL データストアは論理エンティティであり、 VASA Provider で制御されるため、 FlexVol を追加するだけでストレージコンテナの容量を拡張することができます。
