---
permalink: manage/task_set_default_credentials_for_storage_systems.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere 用の ONTAP ツールを使用して、 vCenter Server でストレージシステムのデフォルトクレデンシャルを設定できます。 
---
= ストレージシステムのデフォルトクレデンシャルを設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere 用の ONTAP ツールを使用して、 vCenter Server でストレージシステムのデフォルトクレデンシャルを設定できます。

* 必要なもの *

デフォルトクレデンシャルの作成に使用する vCenter Server を選択しておく必要があります。

* このタスクについて *

ストレージシステムのデフォルトクレデンシャルを設定すると、ONTAP toolsはこれらのクレデンシャルを使用して、ONTAP toolsが検出したストレージシステムにログインします。デフォルトクレデンシャルでログインできない場合は、ストレージシステムに手動でログインする必要があります。ONTAP toolsとSRAは、クラスタレベルまたはSVMレベルでストレージシステムのクレデンシャルの追加をサポートします。ただし、 VASA Provider はクラスタレベルのクレデンシャルとのみ連携します。

* 手順 *

. ONTAP ツールのホームページで、 * 設定 * > * 管理設定 * > * ストレージ・システムのデフォルト・クレデンシャルの設定 * をクリックします。
. ストレージシステムのデフォルトクレデンシャルダイアログボックスで、ストレージシステムのユーザ名とパスワードを入力します。
+
ストレージコントローラのクレデンシャルは、ユーザ名とパスワードのペアに基づいて ONTAP で割り当てられます。ストレージコントローラのクレデンシャルは、管理者アカウントまたはロールベースアクセス制御（ RBAC ）を使用するカスタムアカウントのどちらかです。

+
ONTAP toolsを使用して、ストレージコントローラのユーザ名とパスワードのペアに関連付けられているロールを変更することはできません。ONTAP ツールで使用する新しい ONTAP ユーザロールを変更または作成するには、 System Manager を使用します。

+
を参照してください link:..configure/task_configure_user_role_and_privileges.html["ユーザロールと権限を設定"]ONTAP tools for VMware vSphereのドキュメント_のセクションを参照してください。

. OK * をクリックして、デフォルトクレデンシャルを保存します。


ストレージシステムが報告したためにストレージシステムのクレデンシャルを更新した場合 `Authentication Failure` ステータスが表示されたら、[ストレージシステム]ページの*[すべて再検出]*オプションをクリックします。この場合、ONTAP toolsは新しいクレデンシャルを使用してストレージシステムへの接続を試みます。
