---
permalink: manage/task_monitor_vvols_datastores_and_virtual_machines_using_vvols_dashboard.html 
sidebar: sidebar 
keywords:  
summary: ONTAP ツールの vVol ダッシュボードを使用すると、パフォーマンスを監視し、選択したパラメータに基づいて vCenter Server 内の上位 5 つの SAN および NAS VMware 仮想ボリューム（ vVol ）データストアを表示できます。 
---
= vVol ダッシュボードを使用してパフォーマンスデータを分析します
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ツールの vVol ダッシュボードを使用すると、パフォーマンスを監視し、選択したパラメータに基づいて vCenter Server 内の上位 5 つの SAN および NAS VMware 仮想ボリューム（ vVol ）データストアを表示できます。

* 必要なもの *

* ONTAP 9.6 以前を使用している場合は、 OnCommand API サービス 2.1 以降を有効にしておく必要があります。
+
ONTAP 9.7 以降の場合は、 SAN vVol データストアまたは SAN vVol VM データストアレポートの詳細を取得するために OnCommand API サービスを VASA Provider に登録する必要はありません。

+
https://mysupport.netapp.com/site/global/dashboard[]

* ONTAP 9.3 以降をストレージシステムとして使用している必要があります。


ONTAP から取得された IOPS データは四捨五入されて、 vVol ダッシュボードに表示されます。ONTAP から取得される実際の IOPS 値と vVol ダッシュボードに表示される IOPS 値は異なる可能性があります。9.8 リリースの ONTAP ツールでは、 NFS ベースの VVol データストアについてパフォーマンス監視を実行できます。


NOTE: OnCommand API サービスを初めて登録する場合、 vVol ダッシュボードに SAN vVol データストアのすべてのパフォーマンス指標データが表示されるまでに 15~30 分かかります。

* vVol ダッシュボードのデータは 10 分間隔で定期的に更新されます。
* vCenter Server インスタンスからストレージシステムを追加、変更、または削除した場合は、 vVol ダッシュボードにデータの変更がしばらくの間通知されない可能性があります。
+
これは、 ONTAP API サービスが更新された指標を OnCommand から取得するまでに時間がかかるためです。

* vVol ダッシュボードの概要ポートレットに表示される合計 IOPS の値は、読み取り IOPS の値と書き込み IOPS の値の累積値ではありません。
+
読み取り IOPS 、書き込み IOPS 、合計 IOPS は、 OnCommand API サービスから取得される個別の指標です。OnCommand API サービスから取得される合計 IOPS の値と IOPS の累積値（読み取り IOPS 値 + 書き込み IOPS 値）が異なる場合は、 vVol ダッシュボードでも同様にそれらの IOPS の値が異なります。

* ONTAP 9.8 以降でプロビジョニングされた NFS ベースのデータ VVOL は、 vVol ダッシュボードにパフォーマンス監視用に自動的に登録されます。


* 手順 *

. vSphere Client のホームページで、 * ONTAP tools * をクリックします。
. vCenter Server * ドロップダウン・メニューを使用して、必要な vCenter Server を選択し、データストアを表示します。
. VVol ダッシュボード * をクリックします。
+
Datastores ポートレットには次の詳細が表示されます。

+
** vCenter Server インスタンスの VASA Provider で管理されている vVol データストアの数
** リソースの使用状況とパフォーマンスのパラメータに基づく上位 5 つの vVol データストアは、使用スペース、 IOPS 、またはレイテンシに基づいて、必要な順序でデータストアのリストを変更できます。


. 仮想マシンのポートレットを使用して、仮想マシンの詳細を表示します。
+
仮想マシンのポートレットには以下の詳細が表示されます。

+
** vCenter Server で ONTAP データストアを使用している仮想マシンの数
** IOPS 、レイテンシ、スループット、コミット済み容量、アップタイム、 および論理スペースを使用すると、上位 5 つの仮想マシンを vVol ダッシュボードに表示する方法をカスタマイズできます。






== vVol ダッシュボードのデータ要件

VMware 仮想ボリューム（ vVol ）データストアと仮想マシンの詳細を動的に表示するには、 vVol ダッシュボードのいくつかの重要な要件を確認する必要があります。

次の表は、プロビジョニングされた SAN vVol データストアと仮想マシンのパフォーマンス指標が vVol ダッシュボードに表示されない場合に確認する必要がある項目の概要を示しています。

|===


| * 考慮事項 * | * 概要 * 


 a| 
OnCommand API サービスを初めて導入する場合
 a| 
* ONTAP 9.6 以前のクラスタを使用している場合、 OnCommand API サービス 2.1 以降を使用している。
+
ONTAP 9.7 以降を使用している場合は、 OnCommand API サービスを VASA Provider に登録する必要はありません。

* ネットアップサポートサイトから OnCommand OnCommand サービスをダウンロードしてインストールしたら、 _API サービスインストールおよびセットアップガイドに記載されているインストール手順に従ってください。
* 各 VASA Provider インスタンスに専用の OnCommand API サービスインスタンスが用意されている。
+
複数の VASA Provider インスタンスまたは vCenter Server で OnCommand API サービスを共有しないでください。

* OnCommand API サービスが実行されており、アクセス可能である。




 a| 
ストレージシステム
 a| 
* ONTAP 9.3 以降を使用している。
* ストレージシステムの適切なクレデンシャルを使用している。
* ストレージシステムがアクティブであり、アクセス可能である。
* 選択した仮想マシンで少なくとも 1 つの vVol データストアを使用しており、仮想マシンのディスク上で I/O 処理を実行している。


|===