---
permalink: manage/task_edit_esxi_host_settings.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere 用の ONTAP ツールのダッシュボードを使用して、 ESXi ホストの設定を編集できます。 
---
= ONTAP ツールを使用して ESXi ホストの設定を変更します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere 用の ONTAP ツールのダッシュボードを使用して、 ESXi ホストの設定を編集できます。

* 必要なもの *

vCenter Server インスタンス用の ESXi ホストシステムを設定しておく必要があります。

ESXi ホストが設定されている問題がある場合は、ダッシュボードの ESXi ホストシステムのポートレットに問題が表示されます。問題をクリックすると、問題を搭載した ESXi ホストのホスト名または IP アドレスを確認できます。

* 手順 *

. vSphere Client のホームページで、 * ONTAP tools * をクリックします。
. ESXi ホストの設定を編集します。
+
|===


| * を使用して ESXi ホスト設定を編集します | * これをしなさい ...* 


 a| 
表示されている問題
 a| 
.. [ESXi ホストシステム ] ポートレットで問題をクリックします。
.. 設定を変更する ESXi ホストの名前をクリックします。
.. ESXi ホスト名を右クリックし、 * NetApp ONTAP tools * > * Set recommended values * をクリックします。
.. 必要な設定を変更し、 * OK * をクリックします。




 a| 
vSphere Client のホームページ
 a| 
.. [ * メニュー * > * ホストおよびクラスタ * ] をクリックします。
.. 必要な ESXi ホストを右クリックし、 * NetApp ONTAP tools * > * Set Recommended Value * を選択します。
.. [OK] をクリックします。




 a| 
[ESXiホストシステム]ポートレット
 a| 
.. ONTAP toolsの[Overview]セクションにある*[Traditional dashboard]*タブをクリックします。
.. ESXi ホスト設定の編集 * をクリックします。
.. 設定を変更するホストの設定とステータスタブで ESXi ホスト名を選択し、 * next * （次へ * ）をクリックします。
.. 推奨されるホスト設定タブで必要な設定を選択し、 * 次へ * をクリックします。
.. [Summary] タブで選択内容を確認し、 [* 終了 *] をクリックします。


|===

