---
permalink: manage/task_add_storage_systems.html 
sidebar: sidebar 
keywords:  
summary: Virtual Storage Console \ （ VSC\ ）には手動でストレージシステムを追加できます。 
---
= ストレージシステムを VSC に追加
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Virtual Storage Console （ VSC ）には手動でストレージシステムを追加できます。

* このタスクについて *

Virtual Storage Console （ VSC ）を起動するたび、または * rediscover all * オプションを選択するたびに、使用可能なストレージシステムが自動的に検出されます。

* 手順 *

. ONTAP ツールのホームページを使用して、 VSC にストレージシステムを追加します。
+
** [ * ストレージ・システム * ] > [ * 追加 ] をクリックします。
** [* 概要 *>] 、 [* はじめに ] の順にクリックし、 [ ストレージシステムの追加 ] の下の [* 追加 ] ボタンをクリックします。


. Add Storage System （ストレージシステムの追加）ダイアログボックスで、そのストレージシステムの管理 IP アドレスとクレデンシャルを入力します。
+
クラスタまたは SVM の IPv6 アドレスを使用してストレージシステムを追加することもできます。このダイアログボックスでは、 TLS のデフォルト値とポート番号を変更することもできます。

+
VSC Storage System ページからストレージを追加する場合は、ストレージを配置する vCenter Server インスタンスも指定する必要があります。Add Storage System ダイアログボックスには、使用可能な vCenter Server インスタンスのドロップダウンリストが表示されます。vCenter Server インスタンスにすでに関連付けられているデータセンターにストレージを追加する場合、このオプションは表示されません。

. 必要な情報をすべて追加したら、「 * OK 」をクリックします。

